/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AmazonRegion {
  'id' : string,
  'country' : string,
  'domain' : string,
  'kindleLink' : string,
  'currencySymbol' : string,
  'paperbackButtonText' : string,
  'hardcoverButtonText' : string,
  'kindleButtonColor' : string,
  'paperbackPrice' : string,
  'enabled' : boolean,
  'hardcoverButtonColor' : string,
  'hardcoverLink' : string,
  'kindleButtonText' : string,
  'kindleFontColor' : string,
  'paperbackLink' : string,
  'showKindleUnlimited' : boolean,
  'hardcoverPrice' : string,
  'paperbackFontColor' : string,
  'paperbackButtonColor' : string,
  'hardcoverFontColor' : string,
  'kindlePrice' : string,
}
export interface Announcement {
  'id' : bigint,
  'url' : [] | [string],
  'title' : string,
  'createdAt' : bigint,
  'message' : string,
}
export interface ArtProduct {
  'id' : string,
  'title' : string,
  'imagePath' : [] | [string],
  'purchaseLink' : string,
}
export interface AuthorNote {
  'id' : string,
  'poemSubtitle' : string,
  'noteText' : string,
  'poemTitle' : string,
  'reactions' : {
    'like' : bigint,
    'love' : bigint,
    'laugh' : bigint,
    'dislike' : bigint,
  },
}
export type AuthorNoteReaction = { 'like' : null } |
  { 'love' : null } |
  { 'laugh' : null } |
  { 'dislike' : null };
export interface BackgroundMusicState {
  'musicEnabled' : boolean,
  'tracks' : Array<BackgroundMusicTrack>,
  'playlist' : Array<string>,
  'currentPlaylistIndex' : bigint,
  'activeTrack' : [] | [string],
  'settings' : {
    'volume' : bigint,
    'fadeOutDuration' : bigint,
    'shouldLoop' : boolean,
    'fadeInDuration' : bigint,
  },
}
export interface BackgroundMusicTrack {
  'title' : string,
  'path' : string,
  'uploadTimestamp' : bigint,
  'isActive' : boolean,
  'artist' : string,
}
export interface BolBanner { 'imagePath' : string, 'link' : string }
export interface BookSale {
  'customerName' : [] | [string],
  'salesAmount' : bigint,
  'bookNumber' : bigint,
}
export interface Cell { 'value' : Value, 'name' : string }
export type ChallengeCategory = { 'retail' : null } |
  { 'social' : null };
export interface DictionaryEntry {
  'meaning' : string,
  'word' : string,
  'etymology' : string,
  'examples' : string,
}
export interface DonationEntry {
  'id' : string,
  'name' : string,
  'address' : string,
  'column' : bigint,
  'position' : bigint,
}
export interface EmojiBreakdown {
  'userLike' : bigint,
  'userLove' : bigint,
  'userLaugh' : bigint,
  'autoLike' : bigint,
  'autoLove' : bigint,
  'autoLaugh' : bigint,
  'userDislike' : bigint,
  'autoDislike' : bigint,
}
export interface EmojiRatioConfig {
  'loveMax' : bigint,
  'loveMin' : bigint,
  'laughMax' : bigint,
  'laughMin' : bigint,
  'likeMax' : bigint,
  'likeMin' : bigint,
  'dislikeMax' : bigint,
  'dislikeMin' : bigint,
}
export interface ExperienceChallenge {
  'id' : string,
  'title' : string,
  'specialReward' : [] | [string],
  'rewardPoints' : bigint,
  'description' : string,
  'category' : ChallengeCategory,
}
export interface ExperienceHubTexts {
  'mainSubtitle' : string,
  'socialPageSubtitle' : string,
  'retailCardDescription' : string,
  'gamesPageSubtitle' : string,
  'retailPageSubtitle' : string,
  'socialCardDescription' : string,
  'gamesCardDescription' : string,
}
export interface FileReference { 'hash' : string, 'path' : string }
export interface FooterSettings {
  'businessKvk' : string,
  'businessIban' : string,
  'businessName' : string,
  'businessEmail' : string,
  'businessAddress' : string,
  'footerCaption' : string,
  'businessPhone' : string,
  'businessTaxId' : string,
}
export interface GalleryCarouselPhoto {
  'id' : string,
  'linkUrl' : string,
  'sortOrder' : bigint,
  'path' : string,
  'side' : string,
}
export interface Game {
  'id' : string,
  'title' : string,
  'createdAt' : bigint,
  'playerCount' : string,
  'imageUrl' : [] | [string],
  'gameType' : string,
  'materialsRequired' : string,
  'rules' : Array<string>,
}
export interface GameComment {
  'id' : string,
  'createdAt' : bigint,
  'authorName' : string,
  'gameId' : string,
  'commentText' : string,
  'authorPrincipal' : string,
}
export type GameReaction = { 'like' : null } |
  { 'love' : null } |
  { 'laugh' : null } |
  { 'dislike' : null };
export interface GameReactionCounts {
  'like' : bigint,
  'love' : bigint,
  'laugh' : bigint,
  'dislike' : bigint,
}
export interface HomepageTextBlocks {
  'block1' : TextBlock,
  'block2' : TextBlock,
  'block3' : TextBlock,
}
export interface LeaderboardEntry {
  'id' : string,
  'photoPath' : [] | [string],
  'name' : string,
  'score' : bigint,
}
export interface NewsletterSubscriber {
  'subscribedAt' : bigint,
  'email' : string,
  'principalId' : string,
}
export interface PaymentCountry {
  'id' : string,
  'sortOrder' : bigint,
  'name' : string,
  'continent' : string,
  'enabled' : boolean,
}
export interface PaymentOption {
  'id' : string,
  'methodName' : string,
  'sortOrder' : bigint,
  'link' : string,
  'logoStorageKey' : string,
  'countryId' : string,
  'enabled' : boolean,
  'logoUrl' : string,
  'shippingEuro' : string,
  'buttonColor' : string,
  'priceEuro' : string,
  'fontColor' : string,
  'buzzingEnabled' : boolean,
}
export interface PolicyContent {
  'title' : string,
  'content' : string,
  'policyType' : PolicyType,
}
export type PolicyType = { 'refundAndReturn' : null } |
  { 'privacyPolicy' : null } |
  { 'shippingAndDelivery' : null } |
  { 'termsAndConditions' : null } |
  { 'disclaimerLiability' : null } |
  { 'cookiePolicy' : null } |
  { 'intellectualProperty' : null } |
  { 'promotionalTerms' : null };
export interface Product {
  'id' : string,
  'title' : string,
  'hasCustomImage' : boolean,
  'description' : string,
  'editionType' : string,
  'price' : bigint,
  'frontCoverImagePath' : [] | [string],
  'images' : Array<string>,
}
export type Quarter = { 'q1' : null } |
  { 'q2' : null } |
  { 'q3' : null } |
  { 'q4' : null };
export interface ReflectionBlock {
  'id' : string,
  'poemTitle' : string,
  'reactions' : [] | [
    { 'like' : bigint, 'love' : bigint, 'laugh' : bigint, 'dislike' : bigint }
  ],
  'reflectionChallenges' : Array<string>,
}
export type ReflectionBlockReaction = { 'like' : null } |
  { 'love' : null } |
  { 'laugh' : null } |
  { 'dislike' : null };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface Review {
  'id' : string,
  'bookTitle' : string,
  'photoPath' : [] | [string],
  'starRating' : [] | [bigint],
  'pageNumbers' : string,
  'fullText' : string,
  'reviewerName' : string,
  'snippet' : string,
  'sourceLink' : [] | [string],
  'poemSubTitle' : string,
  'poemTitle' : string,
  'companyBlogSite' : [] | [string],
  'videoUrl' : [] | [string],
  'reactions' : [] | [
    { 'like' : bigint, 'love' : bigint, 'laugh' : bigint, 'dislike' : bigint }
  ],
}
export interface ReviewMilestone {
  'prizeImagePath' : [] | [string],
  'milestone' : bigint,
}
export interface RewardFull {
  'id' : string,
  'photoPath' : [] | [string],
  'pageType' : { 'retail' : null } |
    { 'social' : null },
  'description' : string,
  'availableCount' : [] | [bigint],
  'rewardType' : { 'referral' : null } |
    { 'other' : null } |
    { 'points' : null },
  'claimEmail' : [] | [string],
  'amount' : bigint,
}
export interface RewardInput {
  'id' : string,
  'photoPath' : [] | [string],
  'pageType' : { 'retail' : null } |
    { 'social' : null },
  'description' : string,
  'availableCount' : [] | [bigint],
  'rewardType' : { 'referral' : null } |
    { 'other' : null } |
    { 'points' : null },
  'claimEmail' : [] | [string],
  'amount' : bigint,
}
export interface SharedPaymentLogo {
  'id' : string,
  'name' : string,
  'logoStorageKey' : string,
  'logoUrl' : string,
}
export interface ShortMessage {
  'id' : string,
  'createdAt' : bigint,
  'text' : string,
}
export interface TaxRecord {
  'salesAmount' : bigint,
  'quarter' : Quarter,
  'year' : bigint,
  'taxAmount' : bigint,
}
export interface TextBlock { 'title' : string, 'content' : string }
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserFavourites {
  'shortMessages' : Array<string>,
  'authorNotes' : Array<string>,
  'reflections' : Array<string>,
  'games' : Array<string>,
  'vocabulary' : Array<string>,
}
export interface UserProfile {
  'favouriteReflections' : Array<string>,
  'name' : string,
  'favouriteVocabulary' : Array<string>,
  'favouriteShortMessages' : Array<string>,
  'favouriteGames' : Array<string>,
  'favouriteAuthorNotes' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<string>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<string>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addAmazonRegion' : ActorMethod<[AmazonRegion], undefined>,
  'addAnnouncement' : ActorMethod<[string, string, [] | [string]], bigint>,
  'addArtProduct' : ActorMethod<[ArtProduct], undefined>,
  'addAuthorNote' : ActorMethod<
    [string, string, string],
    { 'ok' : AuthorNote } |
      { 'err' : string }
  >,
  'addBookSale' : ActorMethod<[BookSale], undefined>,
  'addChallenge' : ActorMethod<
    [ChallengeCategory, string, string, bigint, [] | [string]],
    { 'ok' : ExperienceChallenge } |
      { 'err' : string }
  >,
  'addDictionaryEntry' : ActorMethod<[DictionaryEntry], undefined>,
  'addDonation' : ActorMethod<[string, string, bigint, bigint], string>,
  'addFavourite' : ActorMethod<[string, string], boolean>,
  'addGame' : ActorMethod<
    [string, string, string, string, [] | [string], Array<string>],
    string
  >,
  'addGameComment' : ActorMethod<[string, string], string>,
  'addPaymentCountry' : ActorMethod<[PaymentCountry], boolean>,
  'addPaymentOption' : ActorMethod<[PaymentOption], boolean>,
  'addReflectionBlock' : ActorMethod<[ReflectionBlock], undefined>,
  'addRetailLeaderboardEntry' : ActorMethod<[LeaderboardEntry], undefined>,
  'addReview' : ActorMethod<[Review], undefined>,
  'addReviewMilestone' : ActorMethod<[ReviewMilestone], undefined>,
  'addReward' : ActorMethod<[RewardInput], undefined>,
  'addSharedPaymentLogo' : ActorMethod<[SharedPaymentLogo], boolean>,
  'addShortMessage' : ActorMethod<
    [string],
    { 'ok' : ShortMessage } |
      { 'err' : string }
  >,
  'addSocialLeaderboardEntry' : ActorMethod<[LeaderboardEntry], undefined>,
  'addTaxRecord' : ActorMethod<[TaxRecord], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateTax' : ActorMethod<[bigint], string>,
  'createEmissionEffectAnimation' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint],
    { 'animationId' : bigint }
  >,
  'deactivateBackgroundMusicTrack' : ActorMethod<[string], undefined>,
  'deleteAmazonRegion' : ActorMethod<[string], undefined>,
  'deleteArtProduct' : ActorMethod<[string], undefined>,
  'deleteAuthorNote' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteBookSale' : ActorMethod<[bigint], undefined>,
  'deleteChallenge' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteDictionaryEntry' : ActorMethod<[string], undefined>,
  'deleteDonation' : ActorMethod<[string], boolean>,
  'deleteGalleryCarouselPhoto' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteGame' : ActorMethod<[string], boolean>,
  'deleteGameComment' : ActorMethod<[string], boolean>,
  'deletePaymentCountry' : ActorMethod<[string], boolean>,
  'deletePaymentOption' : ActorMethod<[string], boolean>,
  'deleteReflectionBlock' : ActorMethod<[string], undefined>,
  'deleteRetailLeaderboardEntry' : ActorMethod<[string], undefined>,
  'deleteReview' : ActorMethod<[string], undefined>,
  'deleteReviewMilestone' : ActorMethod<[bigint], undefined>,
  'deleteReward' : ActorMethod<[string], undefined>,
  'deleteSharedPaymentLogo' : ActorMethod<[string], boolean>,
  'deleteShortMessage' : ActorMethod<
    [string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteSocialLeaderboardEntry' : ActorMethod<[string], undefined>,
  'deleteTaxRecord' : ActorMethod<[bigint, Quarter], undefined>,
  /**
   * / Admin-only: manually distribute totalAmount emoji reactions across all items
   * / in the given section, randomly within the configured ratio ranges.
   * / Adds to existing counts — never replaces or removes existing data.
   * / section: "reviews" | "challenges" | "authorNotes" | "games"
   */
  'distributeEmojiManually' : ActorMethod<[string, bigint], undefined>,
  'dropFileReference' : ActorMethod<[string], undefined>,
  'ensureBitcoinForAllCountries' : ActorMethod<[], undefined>,
  'ensureCreditcardForAllCountries' : ActorMethod<[], undefined>,
  'ensureEthereumForAllCountries' : ActorMethod<[], undefined>,
  'ensureIcpForAllCountries' : ActorMethod<[], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'getActiveBackgroundMusicTrack' : ActorMethod<[], [] | [string]>,
  'getAllFileReferences' : ActorMethod<[], Array<FileReference>>,
  'getAmazonRegion' : ActorMethod<[string], [] | [AmazonRegion]>,
  'getAmazonRegionForBook' : ActorMethod<[string, string], [] | [AmazonRegion]>,
  'getAmazonRegions' : ActorMethod<[], Array<AmazonRegion>>,
  'getAmazonRegionsByBook' : ActorMethod<[string], Array<AmazonRegion>>,
  /**
   * / Query: is the Amazon region payment section enabled for Anna?
   */
  'getAnnaAmazonEnabled' : ActorMethod<[], boolean>,
  /**
   * / Query: is the Amazon region payment section enabled for
   * / "The Song of Anna the Mermaid" 1st edition?
   */
  'getAnnaSongAmazonEnabled' : ActorMethod<[], boolean>,
  'getAnnouncementRotationInterval' : ActorMethod<[], bigint>,
  'getAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getApproximateBtcAmount' : ActorMethod<[number], number>,
  'getArtProduct' : ActorMethod<[string], [] | [ArtProduct]>,
  'getArtProducts' : ActorMethod<[], Array<ArtProduct>>,
  'getArtProductsSectionData' : ActorMethod<[], { 'description' : string }>,
  'getAuthorNotes' : ActorMethod<[], Array<AuthorNote>>,
  'getBackgroundMusic' : ActorMethod<[], BackgroundMusicState>,
  'getBackgroundMusicEnabled' : ActorMethod<[], boolean>,
  'getBackgroundMusicSettings' : ActorMethod<
    [],
    {
      'volume' : bigint,
      'fadeOutDuration' : bigint,
      'shouldLoop' : boolean,
      'fadeInDuration' : bigint,
    }
  >,
  'getBackgroundMusicTracks' : ActorMethod<[], Array<BackgroundMusicTrack>>,
  'getBitcoinInstructionText' : ActorMethod<[], string>,
  'getBitcoinPaymentAmount' : ActorMethod<
    [],
    { 'currency' : string, 'amount' : string }
  >,
  'getBitcoinPaymentConfig' : ActorMethod<
    [],
    { 'walletAddress' : string, 'contactEmail' : string }
  >,
  'getBitcoinPaymentDetails' : ActorMethod<
    [],
    {
      'qrCodeImagePath' : string,
      'btcEurAmount' : string,
      'btcAddress' : string,
    }
  >,
  'getBitcoinPaymentModalState' : ActorMethod<
    [],
    { 'isOpen' : boolean, 'lastUpdateTimestamp' : bigint }
  >,
  'getBolBanner' : ActorMethod<[], BolBanner>,
  'getBoldedDeliveryInfoText' : ActorMethod<[], string>,
  'getBookSales' : ActorMethod<[], Array<BookSale>>,
  'getBtcAddress' : ActorMethod<[], string>,
  'getBtcEurPrice' : ActorMethod<[], number>,
  'getBtcEurRate' : ActorMethod<[], number>,
  'getBtcExchangeRate' : ActorMethod<[], [] | [number]>,
  'getBtcOrangeColor' : ActorMethod<[], string>,
  'getCallerGameReaction' : ActorMethod<[string], [] | [GameReaction]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChallenges' : ActorMethod<[], Array<ExperienceChallenge>>,
  'getChallengesByCategory' : ActorMethod<
    [ChallengeCategory],
    Array<ExperienceChallenge>
  >,
  'getCopyrightSettings' : ActorMethod<
    [],
    {
      'copyrightStartYear' : bigint,
      'copyrightLine' : string,
      'copyrightYearColor' : string,
      'copyrightLegalText' : string,
    }
  >,
  'getCryptoRates' : ActorMethod<
    [],
    { 'btc' : number, 'eth' : number, 'icp' : number }
  >,
  /**
   * / Query: is the crypto payment system currently enabled?
   */
  'getCryptoSystemEnabled' : ActorMethod<[], boolean>,
  'getCurrentReviewNumber' : ActorMethod<[], bigint>,
  'getDefaultArtProducts' : ActorMethod<[], Array<ArtProduct>>,
  'getDefaultImageStatus' : ActorMethod<
    [],
    {
      'qrCodePath' : string,
      'bolBannerPath' : string,
      'bolBannerRegistered' : boolean,
      'qrCodeRegistered' : boolean,
    }
  >,
  'getDefaultReviews' : ActorMethod<[], Array<Review>>,
  'getDictionaryEntry' : ActorMethod<[string], [] | [DictionaryEntry]>,
  'getDisclaimerText' : ActorMethod<[], string>,
  'getDiscordUrl' : ActorMethod<[], string>,
  /**
   * / Read-only preview: returns what WOULD be distributed if distributeEmojiManually
   * / were called with the given section and totalAmount.
   * / Returns [(itemId, love, like, laugh, dislike)] — does NOT apply anything.
   */
  'getDistributionPreview' : ActorMethod<
    [string, bigint],
    Array<[string, bigint, bigint, bigint, bigint]>
  >,
  /**
   * / Query: is the Amazon region payment section enabled for Emilie?
   */
  'getEmilieAmazonEnabled' : ActorMethod<[], boolean>,
  /**
   * / Query: is the Amazon region payment section enabled for
   * / "Emilie en de Ruïne van Azoth" 1st edition?
   */
  'getEmilieNlAmazonEnabled' : ActorMethod<[], boolean>,
  /**
   * / Query: is the emoji/reaction counter system currently enabled?
   */
  'getEmojiSystemEnabled' : ActorMethod<[], boolean>,
  'getEthAddress' : ActorMethod<[], string>,
  /**
   * / Returns the live ETH/EUR price (calls the mixin's cached CoinGecko fetch).
   */
  'getEthEurPrice' : ActorMethod<[], number>,
  'getEthEurRate' : ActorMethod<[], number>,
  'getExperienceHubTexts' : ActorMethod<[], ExperienceHubTexts>,
  'getFeaturedProductButtonTexts' : ActorMethod<
    [],
    { 'secondProductButtonText' : string, 'firstProductButtonText' : string }
  >,
  'getFileReference' : ActorMethod<[string], [] | [FileReference]>,
  'getFirstProductPrice' : ActorMethod<[], string>,
  'getFooterCopyright' : ActorMethod<[], string>,
  'getFooterSettings' : ActorMethod<[], FooterSettings>,
  'getGalleryCarouselPhotos' : ActorMethod<[], Array<GalleryCarouselPhoto>>,
  'getGameComments' : ActorMethod<[string], Array<GameComment>>,
  'getGameReactionCounts' : ActorMethod<[string], GameReactionCounts>,
  /**
   * / Return game reaction counts including automated inflation.
   */
  'getGameReactionCountsInflated' : ActorMethod<[string], GameReactionCounts>,
  'getGames' : ActorMethod<[], Array<Game>>,
  'getHomepageTextBlocks' : ActorMethod<
    [],
    { 'block1' : TextBlock, 'block2' : TextBlock, 'block3' : TextBlock }
  >,
  'getHomepageTextBlocksAnnaEn' : ActorMethod<[], HomepageTextBlocks>,
  'getHomepageTextBlocksAnnaNl' : ActorMethod<[], HomepageTextBlocks>,
  'getHomepageTextBlocksEmilieEn' : ActorMethod<[], HomepageTextBlocks>,
  'getHomepageTextBlocksEmilieNl' : ActorMethod<[], HomepageTextBlocks>,
  'getIcpAddress' : ActorMethod<[], string>,
  /**
   * / Returns the live ICP/EUR price (calls the mixin's cached CoinGecko fetch).
   */
  'getIcpEurPrice' : ActorMethod<[], number>,
  'getIcpEurRate' : ActorMethod<[], number>,
  /**
   * / Public query: returns the current emoji inflation ratio config.
   */
  'getInflationRatios' : ActorMethod<[], EmojiRatioConfig>,
  /**
   * / Admin-only: full raw distribution stats for the monitor panel.
   */
  'getInflationStats' : ActorMethod<
    [],
    {
      'lastRunTime' : bigint,
      'automatedCounts' : Array<[string, bigint]>,
      'userCounts' : Array<[string, bigint]>,
      'launchTime' : bigint,
      'totalEntities' : bigint,
    }
  >,
  /**
   * / Admin-only: summary grouped by section (review / reflection / author_note / game).
   * / Returns per-section, per-emoji breakdown: automated counts vs user-clicked counts.
   */
  'getInflationSummary' : ActorMethod<
    [],
    {
      'totalAutomated' : bigint,
      'totalUser' : bigint,
      'bySection' : Array<[string, EmojiBreakdown]>,
    }
  >,
  'getInternationalCustomerCheckoutUrl' : ActorMethod<[], string>,
  'getMarktplaatsButtonText' : ActorMethod<[], string>,
  'getMediumUrl' : ActorMethod<[], string>,
  'getMyNewsletterSubscription' : ActorMethod<[], [] | [NewsletterSubscriber]>,
  'getPayPalButtonText' : ActorMethod<[], string>,
  'getPayPalButtonUrl' : ActorMethod<[], string>,
  'getPaymentCountries' : ActorMethod<[], Array<PaymentCountry>>,
  'getPaymentOptions' : ActorMethod<[], Array<PaymentOption>>,
  'getPaymentOptionsByCountry' : ActorMethod<[string], Array<PaymentOption>>,
  'getPolicyContent' : ActorMethod<[PolicyType], PolicyContent>,
  'getPopupInstructions' : ActorMethod<
    [],
    { 'mollieInstruction' : string, 'revolutInstruction' : string }
  >,
  'getProductByKey' : ActorMethod<[string], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getPromotionalTermsContent' : ActorMethod<[], string>,
  'getPurchaseButtonInstructionalText' : ActorMethod<[], string>,
  'getPurchaseButtonUrl' : ActorMethod<[], string>,
  'getQrCodeImagePath' : ActorMethod<[], string>,
  'getRandomArtProductsLayout' : ActorMethod<
    [bigint],
    { 'x' : bigint, 'y' : bigint, 'rotation' : bigint, 'imageIndex' : bigint }
  >,
  'getRandomCharacters' : ActorMethod<
    [bigint],
    Array<{ 'character' : string } | { 'position' : bigint }>
  >,
  'getRandomEmissionCharacters' : ActorMethod<
    [bigint, { 'left' : null } | { 'right' : null }],
    Array<string>
  >,
  'getRandomGalleryLayout' : ActorMethod<
    [bigint],
    { 'x' : bigint, 'y' : bigint, 'rotation' : bigint, 'imageIndex' : bigint }
  >,
  'getReflectionBlock' : ActorMethod<[string], [] | [ReflectionBlock]>,
  'getReflectionBlocks' : ActorMethod<[], Array<ReflectionBlock>>,
  'getRetailLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getRetailRewards' : ActorMethod<[], Array<RewardFull>>,
  'getReview' : ActorMethod<[string], [] | [Review]>,
  'getReviewBookTitles' : ActorMethod<[], Array<string>>,
  'getReviewEmojiCountsV2' : ActorMethod<
    [string],
    { 'like' : bigint, 'love' : bigint, 'laugh' : bigint, 'dislike' : bigint }
  >,
  'getReviewMilestones' : ActorMethod<[], Array<ReviewMilestone>>,
  'getReviews' : ActorMethod<[], Array<Review>>,
  'getReviewsByBookTitle' : ActorMethod<[string], Array<Review>>,
  'getRevolutPayButtonTextFirstProduct' : ActorMethod<[], string>,
  'getRevolutPayButtonTextSecondProduct' : ActorMethod<[], string>,
  'getRevolutPayButtonUrl' : ActorMethod<[], string>,
  'getRoadmapSectionData' : ActorMethod<
    [],
    {
      'title' : string,
      'currentReviews' : bigint,
      'progressPercentage' : bigint,
      'description' : string,
    }
  >,
  'getSecondProductPayPalUrl' : ActorMethod<[], string>,
  'getSecondProductPrice' : ActorMethod<[], string>,
  'getSharedPaymentLogos' : ActorMethod<[], Array<SharedPaymentLogo>>,
  'getShippingNote' : ActorMethod<[], string>,
  'getSocialLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getSocialRewards' : ActorMethod<[], Array<RewardFull>>,
  'getSpiralFlowerPattern' : ActorMethod<
    [bigint, bigint, string],
    {
      'centerX' : bigint,
      'centerY' : bigint,
      'isBlooming' : boolean,
      'bloomDurationMs' : bigint,
      'patternId' : bigint,
      'spiralColor' : string,
      'bloomStartTime' : bigint,
    }
  >,
  'getSubmitProofEmail' : ActorMethod<[], string>,
  'getTaxRecords' : ActorMethod<[], Array<TaxRecord>>,
  'getTelegramUrl' : ActorMethod<[], string>,
  'getTiktokUrl' : ActorMethod<[], string>,
  'getUserFavourites' : ActorMethod<[], UserFavourites>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserReviewReactionV2' : ActorMethod<[string], [] | [string]>,
  'getViaMarktplaatsButtonUrl' : ActorMethod<[], string>,
  'getViaVintedButtonUrl' : ActorMethod<[], string>,
  'getVintedButtonText' : ActorMethod<[], string>,
  'getWatermarkedCharacters' : ActorMethod<[bigint], Array<string>>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listDictionaryEntries' : ActorMethod<[], Array<DictionaryEntry>>,
  'listDonations' : ActorMethod<[], Array<DonationEntry>>,
  'listFileReferences' : ActorMethod<[], Array<FileReference>>,
  'listNewsletterSubscribers' : ActorMethod<[], Array<NewsletterSubscriber>>,
  'listShortMessages' : ActorMethod<[], Array<ShortMessage>>,
  'reactToAuthorNote' : ActorMethod<
    [string, AuthorNoteReaction],
    { 'ok' : AuthorNote } |
      { 'err' : string }
  >,
  'reactToGame' : ActorMethod<[string, GameReaction], boolean>,
  /**
   * / React to a game and track user engagement for inflation weighting.
   */
  'reactToGameAndTrack' : ActorMethod<[string, GameReaction], boolean>,
  'reactToReflectionBlock' : ActorMethod<
    [string, ReflectionBlockReaction],
    { 'ok' : ReflectionBlock } |
      { 'err' : string }
  >,
  'reactToReviewV2' : ActorMethod<[string, string], undefined>,
  'registerFileReference' : ActorMethod<[string, string], undefined>,
  'removeAmazonRegionFromBook' : ActorMethod<[string, string], undefined>,
  'removeAnnouncement' : ActorMethod<[bigint], boolean>,
  'removeBackgroundMusicTrack' : ActorMethod<[string], undefined>,
  'removeFavourite' : ActorMethod<[string, string], boolean>,
  'removeNewsletterSubscriber' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'reorderGalleryCarouselPhotos' : ActorMethod<
    [Array<string>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Admin-only: reset the manual distribution counts (e.g. for a clean slate).
   * / Does NOT touch per-item user reaction data.
   */
  'resetInflationCounts' : ActorMethod<[], undefined>,
  'saveAmazonRegionForBook' : ActorMethod<[string, AmazonRegion], undefined>,
  'saveAmazonRegionsByBook' : ActorMethod<
    [string, Array<AmazonRegion>],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveGalleryCarouselPhoto' : ActorMethod<
    [string, string, string, bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'schema' : ActorMethod<[], string>,
  'setActiveBackgroundMusicTrack' : ActorMethod<[string], undefined>,
  'setAmazonRegions' : ActorMethod<[Array<AmazonRegion>], undefined>,
  /**
   * / Admin-only: show or hide the Amazon region payment section for Anna.
   */
  'setAnnaAmazonEnabled' : ActorMethod<[boolean], undefined>,
  /**
   * / Admin-only: show or hide the Amazon region payment section for
   * / "The Song of Anna the Mermaid" 1st edition.
   */
  'setAnnaSongAmazonEnabled' : ActorMethod<[boolean], undefined>,
  'setAnnouncementRotationInterval' : ActorMethod<[bigint], boolean>,
  'setBackgroundMusicEnabled' : ActorMethod<[boolean], undefined>,
  'setBackgroundMusicPlaylist' : ActorMethod<[Array<string>], undefined>,
  'setBtcContactEmail' : ActorMethod<[string], boolean>,
  'setBtcWalletAddress' : ActorMethod<[string], boolean>,
  /**
   * / Admin-only: enable or disable the crypto payment system.
   */
  'setCryptoSystemEnabled' : ActorMethod<[boolean], undefined>,
  /**
   * / Admin-only: show or hide the Amazon region payment section for Emilie.
   */
  'setEmilieAmazonEnabled' : ActorMethod<[boolean], undefined>,
  /**
   * / Admin-only: show or hide the Amazon region payment section for
   * / "Emilie en de Ruïne van Azoth" 1st edition.
   */
  'setEmilieNlAmazonEnabled' : ActorMethod<[boolean], undefined>,
  /**
   * / Admin-only: enable or disable the emoji inflation engine and reaction counters.
   */
  'setEmojiSystemEnabled' : ActorMethod<[boolean], undefined>,
  'setEthWalletAddress' : ActorMethod<[string], boolean>,
  'setIcpWalletAddress' : ActorMethod<[string], boolean>,
  /**
   * / Admin-only: update the emoji inflation ratio config.
   */
  'setInflationRatios' : ActorMethod<[EmojiRatioConfig], undefined>,
  'subscribeToNewsletter' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  /**
   * / No-op: kept for frontend binding compatibility.
   * / Automatic inflation has been removed. All emoji distribution is manual via distributeEmojiManually().
   */
  'triggerInflation' : ActorMethod<[], undefined>,
  'unsubscribeFromNewsletter' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateAmazonRegion' : ActorMethod<[AmazonRegion], undefined>,
  'updateAnnouncement' : ActorMethod<
    [bigint, string, string, [] | [string]],
    boolean
  >,
  'updateArtProduct' : ActorMethod<[ArtProduct], undefined>,
  'updateAuthorNote' : ActorMethod<
    [string, string, string, string],
    { 'ok' : AuthorNote } |
      { 'err' : string }
  >,
  'updateBackgroundMusicSettings' : ActorMethod<
    [
      {
        'volume' : bigint,
        'fadeOutDuration' : bigint,
        'shouldLoop' : boolean,
        'fadeInDuration' : bigint,
      },
    ],
    undefined
  >,
  'updateBookSale' : ActorMethod<[BookSale], undefined>,
  'updateBtcExchangeRate' : ActorMethod<[number], undefined>,
  'updateChallenge' : ActorMethod<
    [string, ChallengeCategory, string, string, bigint, [] | [string]],
    { 'ok' : ExperienceChallenge } |
      { 'err' : string }
  >,
  'updateCopyrightSettings' : ActorMethod<
    [string, bigint, string, string],
    undefined
  >,
  'updateCurrentReviewNumber' : ActorMethod<[bigint], undefined>,
  'updateDictionaryEntry' : ActorMethod<[DictionaryEntry], undefined>,
  'updateDonation' : ActorMethod<
    [string, string, string, bigint, bigint],
    boolean
  >,
  'updateExperienceHubTexts' : ActorMethod<[ExperienceHubTexts], undefined>,
  'updateFooterSettings' : ActorMethod<[FooterSettings], undefined>,
  'updateGame' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      [] | [string],
      [] | [Array<string>],
    ],
    boolean
  >,
  'updateHomepageTextBlocks' : ActorMethod<
    [{ 'block1' : TextBlock, 'block2' : TextBlock, 'block3' : TextBlock }],
    undefined
  >,
  'updateHomepageTextBlocksAnnaEn' : ActorMethod<
    [HomepageTextBlocks],
    undefined
  >,
  'updateHomepageTextBlocksAnnaNl' : ActorMethod<
    [HomepageTextBlocks],
    undefined
  >,
  'updateHomepageTextBlocksEmilieEn' : ActorMethod<
    [HomepageTextBlocks],
    undefined
  >,
  'updateHomepageTextBlocksEmilieNl' : ActorMethod<
    [HomepageTextBlocks],
    undefined
  >,
  'updatePaymentCountry' : ActorMethod<[PaymentCountry], boolean>,
  'updatePaymentOption' : ActorMethod<[PaymentOption], boolean>,
  'updatePolicyContent' : ActorMethod<[PolicyType, string], undefined>,
  'updateProductByKey' : ActorMethod<[string, Product], boolean>,
  'updatePromotionalTermsContent' : ActorMethod<[string], undefined>,
  'updateReflectionBlock' : ActorMethod<[ReflectionBlock], undefined>,
  'updateRetailLeaderboardEntry' : ActorMethod<[LeaderboardEntry], undefined>,
  'updateReview' : ActorMethod<[Review], undefined>,
  'updateReviewMilestone' : ActorMethod<[ReviewMilestone], undefined>,
  'updateReward' : ActorMethod<[RewardInput], undefined>,
  'updateSharedPaymentLogo' : ActorMethod<[SharedPaymentLogo], boolean>,
  'updateShortMessage' : ActorMethod<
    [string, string],
    { 'ok' : ShortMessage } |
      { 'err' : string }
  >,
  'updateSocialLeaderboardEntry' : ActorMethod<[LeaderboardEntry], undefined>,
  'updateSubmitProofEmail' : ActorMethod<[string], undefined>,
  'updateTaxRecord' : ActorMethod<[TaxRecord], undefined>,
  'uploadBackgroundMusicTrack' : ActorMethod<[BackgroundMusicTrack], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];