/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AmazonRegion = IDL.Record({
  'id' : IDL.Text,
  'country' : IDL.Text,
  'domain' : IDL.Text,
  'kindleLink' : IDL.Text,
  'currencySymbol' : IDL.Text,
  'paperbackButtonText' : IDL.Text,
  'hardcoverButtonText' : IDL.Text,
  'kindleButtonColor' : IDL.Text,
  'paperbackPrice' : IDL.Text,
  'enabled' : IDL.Bool,
  'hardcoverButtonColor' : IDL.Text,
  'hardcoverLink' : IDL.Text,
  'kindleButtonText' : IDL.Text,
  'kindleFontColor' : IDL.Text,
  'paperbackLink' : IDL.Text,
  'showKindleUnlimited' : IDL.Bool,
  'hardcoverPrice' : IDL.Text,
  'paperbackFontColor' : IDL.Text,
  'paperbackButtonColor' : IDL.Text,
  'hardcoverFontColor' : IDL.Text,
  'kindlePrice' : IDL.Text,
});
export const ArtProduct = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'imagePath' : IDL.Opt(IDL.Text),
  'purchaseLink' : IDL.Text,
});
export const AuthorNote = IDL.Record({
  'id' : IDL.Text,
  'poemSubtitle' : IDL.Text,
  'noteText' : IDL.Text,
  'poemTitle' : IDL.Text,
  'reactions' : IDL.Record({
    'like' : IDL.Nat,
    'love' : IDL.Nat,
    'laugh' : IDL.Nat,
    'dislike' : IDL.Nat,
  }),
});
export const BookSale = IDL.Record({
  'customerName' : IDL.Opt(IDL.Text),
  'salesAmount' : IDL.Nat,
  'bookNumber' : IDL.Nat,
});
export const ChallengeCategory = IDL.Variant({
  'retail' : IDL.Null,
  'social' : IDL.Null,
});
export const ExperienceChallenge = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'specialReward' : IDL.Opt(IDL.Text),
  'rewardPoints' : IDL.Nat,
  'description' : IDL.Text,
  'category' : ChallengeCategory,
});
export const DictionaryEntry = IDL.Record({
  'meaning' : IDL.Text,
  'word' : IDL.Text,
  'etymology' : IDL.Text,
  'examples' : IDL.Text,
});
export const PaymentCountry = IDL.Record({
  'id' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'continent' : IDL.Text,
  'enabled' : IDL.Bool,
});
export const PaymentOption = IDL.Record({
  'id' : IDL.Text,
  'methodName' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'link' : IDL.Text,
  'logoStorageKey' : IDL.Text,
  'countryId' : IDL.Text,
  'enabled' : IDL.Bool,
  'logoUrl' : IDL.Text,
  'shippingEuro' : IDL.Text,
  'buttonColor' : IDL.Text,
  'priceEuro' : IDL.Text,
  'fontColor' : IDL.Text,
  'buzzingEnabled' : IDL.Bool,
});
export const ReflectionBlock = IDL.Record({
  'id' : IDL.Text,
  'poemTitle' : IDL.Text,
  'reactions' : IDL.Opt(
    IDL.Record({
      'like' : IDL.Nat,
      'love' : IDL.Nat,
      'laugh' : IDL.Nat,
      'dislike' : IDL.Nat,
    })
  ),
  'reflectionChallenges' : IDL.Vec(IDL.Text),
});
export const LeaderboardEntry = IDL.Record({
  'id' : IDL.Text,
  'photoPath' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'score' : IDL.Nat,
});
export const Review = IDL.Record({
  'id' : IDL.Text,
  'bookTitle' : IDL.Text,
  'photoPath' : IDL.Opt(IDL.Text),
  'starRating' : IDL.Opt(IDL.Nat),
  'pageNumbers' : IDL.Text,
  'fullText' : IDL.Text,
  'reviewerName' : IDL.Text,
  'snippet' : IDL.Text,
  'sourceLink' : IDL.Opt(IDL.Text),
  'poemSubTitle' : IDL.Text,
  'poemTitle' : IDL.Text,
  'companyBlogSite' : IDL.Opt(IDL.Text),
  'videoUrl' : IDL.Opt(IDL.Text),
  'reactions' : IDL.Opt(
    IDL.Record({
      'like' : IDL.Nat,
      'love' : IDL.Nat,
      'laugh' : IDL.Nat,
      'dislike' : IDL.Nat,
    })
  ),
});
export const ReviewMilestone = IDL.Record({
  'prizeImagePath' : IDL.Opt(IDL.Text),
  'milestone' : IDL.Nat,
});
export const RewardInput = IDL.Record({
  'id' : IDL.Text,
  'photoPath' : IDL.Opt(IDL.Text),
  'pageType' : IDL.Variant({ 'retail' : IDL.Null, 'social' : IDL.Null }),
  'description' : IDL.Text,
  'availableCount' : IDL.Opt(IDL.Nat),
  'rewardType' : IDL.Variant({
    'referral' : IDL.Null,
    'other' : IDL.Null,
    'points' : IDL.Null,
  }),
  'claimEmail' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
});
export const SharedPaymentLogo = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'logoStorageKey' : IDL.Text,
  'logoUrl' : IDL.Text,
});
export const ShortMessage = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
});
export const Quarter = IDL.Variant({
  'q1' : IDL.Null,
  'q2' : IDL.Null,
  'q3' : IDL.Null,
  'q4' : IDL.Null,
});
export const TaxRecord = IDL.Record({
  'salesAmount' : IDL.Nat,
  'quarter' : Quarter,
  'year' : IDL.Nat,
  'taxAmount' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const FileReference = IDL.Record({
  'hash' : IDL.Text,
  'path' : IDL.Text,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'message' : IDL.Text,
});
export const BackgroundMusicTrack = IDL.Record({
  'title' : IDL.Text,
  'path' : IDL.Text,
  'uploadTimestamp' : IDL.Int,
  'isActive' : IDL.Bool,
  'artist' : IDL.Text,
});
export const BackgroundMusicState = IDL.Record({
  'musicEnabled' : IDL.Bool,
  'tracks' : IDL.Vec(BackgroundMusicTrack),
  'playlist' : IDL.Vec(IDL.Text),
  'currentPlaylistIndex' : IDL.Nat,
  'activeTrack' : IDL.Opt(IDL.Text),
  'settings' : IDL.Record({
    'volume' : IDL.Nat,
    'fadeOutDuration' : IDL.Nat,
    'shouldLoop' : IDL.Bool,
    'fadeInDuration' : IDL.Nat,
  }),
});
export const BolBanner = IDL.Record({
  'imagePath' : IDL.Text,
  'link' : IDL.Text,
});
export const GameReaction = IDL.Variant({
  'like' : IDL.Null,
  'love' : IDL.Null,
  'laugh' : IDL.Null,
  'dislike' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'favouriteReflections' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'favouriteVocabulary' : IDL.Vec(IDL.Text),
  'favouriteShortMessages' : IDL.Vec(IDL.Text),
  'favouriteGames' : IDL.Vec(IDL.Text),
  'favouriteAuthorNotes' : IDL.Vec(IDL.Text),
});
export const ExperienceHubTexts = IDL.Record({
  'mainSubtitle' : IDL.Text,
  'socialPageSubtitle' : IDL.Text,
  'retailCardDescription' : IDL.Text,
  'gamesPageSubtitle' : IDL.Text,
  'retailPageSubtitle' : IDL.Text,
  'socialCardDescription' : IDL.Text,
  'gamesCardDescription' : IDL.Text,
});
export const FooterSettings = IDL.Record({
  'businessKvk' : IDL.Text,
  'businessIban' : IDL.Text,
  'businessName' : IDL.Text,
  'businessEmail' : IDL.Text,
  'businessAddress' : IDL.Text,
  'footerCaption' : IDL.Text,
  'businessPhone' : IDL.Text,
  'businessTaxId' : IDL.Text,
});
export const GalleryCarouselPhoto = IDL.Record({
  'id' : IDL.Text,
  'linkUrl' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'path' : IDL.Text,
  'side' : IDL.Text,
});
export const GameComment = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'authorName' : IDL.Text,
  'gameId' : IDL.Text,
  'commentText' : IDL.Text,
  'authorPrincipal' : IDL.Text,
});
export const GameReactionCounts = IDL.Record({
  'like' : IDL.Nat,
  'love' : IDL.Nat,
  'laugh' : IDL.Nat,
  'dislike' : IDL.Nat,
});
export const Game = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'playerCount' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'gameType' : IDL.Text,
  'materialsRequired' : IDL.Text,
  'rules' : IDL.Vec(IDL.Text),
});
export const TextBlock = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const HomepageTextBlocks = IDL.Record({
  'block1' : TextBlock,
  'block2' : TextBlock,
  'block3' : TextBlock,
});
export const EmojiRatioConfig = IDL.Record({
  'loveMax' : IDL.Nat,
  'loveMin' : IDL.Nat,
  'laughMax' : IDL.Nat,
  'laughMin' : IDL.Nat,
  'likeMax' : IDL.Nat,
  'likeMin' : IDL.Nat,
  'dislikeMax' : IDL.Nat,
  'dislikeMin' : IDL.Nat,
});
export const EmojiBreakdown = IDL.Record({
  'userLike' : IDL.Nat,
  'userLove' : IDL.Nat,
  'userLaugh' : IDL.Nat,
  'autoLike' : IDL.Nat,
  'autoLove' : IDL.Nat,
  'autoLaugh' : IDL.Nat,
  'userDislike' : IDL.Nat,
  'autoDislike' : IDL.Nat,
});
export const NewsletterSubscriber = IDL.Record({
  'subscribedAt' : IDL.Int,
  'email' : IDL.Text,
  'principalId' : IDL.Text,
});
export const PolicyType = IDL.Variant({
  'refundAndReturn' : IDL.Null,
  'privacyPolicy' : IDL.Null,
  'shippingAndDelivery' : IDL.Null,
  'termsAndConditions' : IDL.Null,
  'disclaimerLiability' : IDL.Null,
  'cookiePolicy' : IDL.Null,
  'intellectualProperty' : IDL.Null,
  'promotionalTerms' : IDL.Null,
});
export const PolicyContent = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'policyType' : PolicyType,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'hasCustomImage' : IDL.Bool,
  'description' : IDL.Text,
  'editionType' : IDL.Text,
  'price' : IDL.Nat,
  'frontCoverImagePath' : IDL.Opt(IDL.Text),
  'images' : IDL.Vec(IDL.Text),
});
export const RewardFull = IDL.Record({
  'id' : IDL.Text,
  'photoPath' : IDL.Opt(IDL.Text),
  'pageType' : IDL.Variant({ 'retail' : IDL.Null, 'social' : IDL.Null }),
  'description' : IDL.Text,
  'availableCount' : IDL.Opt(IDL.Nat),
  'rewardType' : IDL.Variant({
    'referral' : IDL.Null,
    'other' : IDL.Null,
    'points' : IDL.Null,
  }),
  'claimEmail' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
});
export const UserFavourites = IDL.Record({
  'shortMessages' : IDL.Vec(IDL.Text),
  'authorNotes' : IDL.Vec(IDL.Text),
  'reflections' : IDL.Vec(IDL.Text),
  'games' : IDL.Vec(IDL.Text),
  'vocabulary' : IDL.Vec(IDL.Text),
});
export const DonationEntry = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'column' : IDL.Nat,
  'position' : IDL.Nat,
});
export const AuthorNoteReaction = IDL.Variant({
  'like' : IDL.Null,
  'love' : IDL.Null,
  'laugh' : IDL.Null,
  'dislike' : IDL.Null,
});
export const ReflectionBlockReaction = IDL.Variant({
  'like' : IDL.Null,
  'love' : IDL.Null,
  'laugh' : IDL.Null,
  'dislike' : IDL.Null,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addAmazonRegion' : IDL.Func([AmazonRegion], [], []),
  'addAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'addArtProduct' : IDL.Func([ArtProduct], [], []),
  'addAuthorNote' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : AuthorNote, 'err' : IDL.Text })],
      [],
    ),
  'addBookSale' : IDL.Func([BookSale], [], []),
  'addChallenge' : IDL.Func(
      [ChallengeCategory, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : ExperienceChallenge, 'err' : IDL.Text })],
      [],
    ),
  'addDictionaryEntry' : IDL.Func([DictionaryEntry], [], []),
  'addDonation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'addFavourite' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'addGame' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [IDL.Text],
      [],
    ),
  'addGameComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'addPaymentCountry' : IDL.Func([PaymentCountry], [IDL.Bool], []),
  'addPaymentOption' : IDL.Func([PaymentOption], [IDL.Bool], []),
  'addReflectionBlock' : IDL.Func([ReflectionBlock], [], []),
  'addRetailLeaderboardEntry' : IDL.Func([LeaderboardEntry], [], []),
  'addReview' : IDL.Func([Review], [], []),
  'addReviewMilestone' : IDL.Func([ReviewMilestone], [], []),
  'addReward' : IDL.Func([RewardInput], [], []),
  'addSharedPaymentLogo' : IDL.Func([SharedPaymentLogo], [IDL.Bool], []),
  'addShortMessage' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : ShortMessage, 'err' : IDL.Text })],
      [],
    ),
  'addSocialLeaderboardEntry' : IDL.Func([LeaderboardEntry], [], []),
  'addTaxRecord' : IDL.Func([TaxRecord], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateTax' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'createEmissionEffectAnimation' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Record({ 'animationId' : IDL.Nat })],
      [],
    ),
  'deactivateBackgroundMusicTrack' : IDL.Func([IDL.Text], [], []),
  'deleteAmazonRegion' : IDL.Func([IDL.Text], [], []),
  'deleteArtProduct' : IDL.Func([IDL.Text], [], []),
  'deleteAuthorNote' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteBookSale' : IDL.Func([IDL.Nat], [], []),
  'deleteChallenge' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteDictionaryEntry' : IDL.Func([IDL.Text], [], []),
  'deleteDonation' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteGalleryCarouselPhoto' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteGame' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteGameComment' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deletePaymentCountry' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deletePaymentOption' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteReflectionBlock' : IDL.Func([IDL.Text], [], []),
  'deleteRetailLeaderboardEntry' : IDL.Func([IDL.Text], [], []),
  'deleteReview' : IDL.Func([IDL.Text], [], []),
  'deleteReviewMilestone' : IDL.Func([IDL.Nat], [], []),
  'deleteReward' : IDL.Func([IDL.Text], [], []),
  'deleteSharedPaymentLogo' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteShortMessage' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteSocialLeaderboardEntry' : IDL.Func([IDL.Text], [], []),
  'deleteTaxRecord' : IDL.Func([IDL.Nat, Quarter], [], []),
  'distributeEmojiManually' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'dropFileReference' : IDL.Func([IDL.Text], [], []),
  'ensureBitcoinForAllCountries' : IDL.Func([], [], []),
  'ensureCreditcardForAllCountries' : IDL.Func([], [], []),
  'ensureEthereumForAllCountries' : IDL.Func([], [], []),
  'ensureIcpForAllCountries' : IDL.Func([], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getActiveBackgroundMusicTrack' : IDL.Func(
      [],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getAllFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
  'getAmazonRegion' : IDL.Func([IDL.Text], [IDL.Opt(AmazonRegion)], ['query']),
  'getAmazonRegionForBook' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(AmazonRegion)],
      ['query'],
    ),
  'getAmazonRegions' : IDL.Func([], [IDL.Vec(AmazonRegion)], ['query']),
  'getAmazonRegionsByBook' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AmazonRegion)],
      ['query'],
    ),
  'getAnnaAmazonEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'getAnnaSongAmazonEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'getAnnouncementRotationInterval' : IDL.Func([], [IDL.Nat], ['query']),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getApproximateBtcAmount' : IDL.Func([IDL.Float64], [IDL.Float64], ['query']),
  'getArtProduct' : IDL.Func([IDL.Text], [IDL.Opt(ArtProduct)], ['query']),
  'getArtProducts' : IDL.Func([], [IDL.Vec(ArtProduct)], ['query']),
  'getArtProductsSectionData' : IDL.Func(
      [],
      [IDL.Record({ 'description' : IDL.Text })],
      ['query'],
    ),
  'getAuthorNotes' : IDL.Func([], [IDL.Vec(AuthorNote)], ['query']),
  'getBackgroundMusic' : IDL.Func([], [BackgroundMusicState], ['query']),
  'getBackgroundMusicEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'getBackgroundMusicSettings' : IDL.Func(
      [],
      [
        IDL.Record({
          'volume' : IDL.Nat,
          'fadeOutDuration' : IDL.Nat,
          'shouldLoop' : IDL.Bool,
          'fadeInDuration' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getBackgroundMusicTracks' : IDL.Func(
      [],
      [IDL.Vec(BackgroundMusicTrack)],
      ['query'],
    ),
  'getBitcoinInstructionText' : IDL.Func([], [IDL.Text], ['query']),
  'getBitcoinPaymentAmount' : IDL.Func(
      [],
      [IDL.Record({ 'currency' : IDL.Text, 'amount' : IDL.Text })],
      ['query'],
    ),
  'getBitcoinPaymentConfig' : IDL.Func(
      [],
      [IDL.Record({ 'walletAddress' : IDL.Text, 'contactEmail' : IDL.Text })],
      ['query'],
    ),
  'getBitcoinPaymentDetails' : IDL.Func(
      [],
      [
        IDL.Record({
          'qrCodeImagePath' : IDL.Text,
          'btcEurAmount' : IDL.Text,
          'btcAddress' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getBitcoinPaymentModalState' : IDL.Func(
      [],
      [IDL.Record({ 'isOpen' : IDL.Bool, 'lastUpdateTimestamp' : IDL.Int })],
      ['query'],
    ),
  'getBolBanner' : IDL.Func([], [BolBanner], ['query']),
  'getBoldedDeliveryInfoText' : IDL.Func([], [IDL.Text], ['query']),
  'getBookSales' : IDL.Func([], [IDL.Vec(BookSale)], ['query']),
  'getBtcAddress' : IDL.Func([], [IDL.Text], ['query']),
  'getBtcEurPrice' : IDL.Func([], [IDL.Float64], []),
  'getBtcEurRate' : IDL.Func([], [IDL.Float64], []),
  'getBtcExchangeRate' : IDL.Func([], [IDL.Opt(IDL.Float64)], ['query']),
  'getBtcOrangeColor' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerGameReaction' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(GameReaction)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChallenges' : IDL.Func([], [IDL.Vec(ExperienceChallenge)], ['query']),
  'getChallengesByCategory' : IDL.Func(
      [ChallengeCategory],
      [IDL.Vec(ExperienceChallenge)],
      ['query'],
    ),
  'getCopyrightSettings' : IDL.Func(
      [],
      [
        IDL.Record({
          'copyrightStartYear' : IDL.Nat,
          'copyrightLine' : IDL.Text,
          'copyrightYearColor' : IDL.Text,
          'copyrightLegalText' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getCryptoRates' : IDL.Func(
      [],
      [
        IDL.Record({
          'btc' : IDL.Float64,
          'eth' : IDL.Float64,
          'icp' : IDL.Float64,
        }),
      ],
      [],
    ),
  'getCryptoSystemEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'getCurrentReviewNumber' : IDL.Func([], [IDL.Nat], ['query']),
  'getDefaultArtProducts' : IDL.Func([], [IDL.Vec(ArtProduct)], ['query']),
  'getDefaultImageStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'qrCodePath' : IDL.Text,
          'bolBannerPath' : IDL.Text,
          'bolBannerRegistered' : IDL.Bool,
          'qrCodeRegistered' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'getDefaultReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getDictionaryEntry' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DictionaryEntry)],
      ['query'],
    ),
  'getDisclaimerText' : IDL.Func([], [IDL.Text], ['query']),
  'getDiscordUrl' : IDL.Func([], [IDL.Text], ['query']),
  'getDistributionPreview' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getEmilieAmazonEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'getEmilieNlAmazonEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'getEmojiSystemEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'getEthAddress' : IDL.Func([], [IDL.Text], ['query']),
  'getEthEurPrice' : IDL.Func([], [IDL.Float64], []),
  'getEthEurRate' : IDL.Func([], [IDL.Float64], []),
  'getExperienceHubTexts' : IDL.Func([], [ExperienceHubTexts], ['query']),
  'getFeaturedProductButtonTexts' : IDL.Func(
      [],
      [
        IDL.Record({
          'secondProductButtonText' : IDL.Text,
          'firstProductButtonText' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getFileReference' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(FileReference)],
      ['query'],
    ),
  'getFirstProductPrice' : IDL.Func([], [IDL.Text], ['query']),
  'getFooterCopyright' : IDL.Func([], [IDL.Text], ['query']),
  'getFooterSettings' : IDL.Func([], [FooterSettings], ['query']),
  'getGalleryCarouselPhotos' : IDL.Func(
      [],
      [IDL.Vec(GalleryCarouselPhoto)],
      ['query'],
    ),
  'getGameComments' : IDL.Func([IDL.Text], [IDL.Vec(GameComment)], ['query']),
  'getGameReactionCounts' : IDL.Func(
      [IDL.Text],
      [GameReactionCounts],
      ['query'],
    ),
  'getGameReactionCountsInflated' : IDL.Func(
      [IDL.Text],
      [GameReactionCounts],
      ['query'],
    ),
  'getGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'getHomepageTextBlocks' : IDL.Func(
      [],
      [
        IDL.Record({
          'block1' : TextBlock,
          'block2' : TextBlock,
          'block3' : TextBlock,
        }),
      ],
      ['query'],
    ),
  'getHomepageTextBlocksAnnaEn' : IDL.Func([], [HomepageTextBlocks], ['query']),
  'getHomepageTextBlocksAnnaNl' : IDL.Func([], [HomepageTextBlocks], ['query']),
  'getHomepageTextBlocksEmilieEn' : IDL.Func(
      [],
      [HomepageTextBlocks],
      ['query'],
    ),
  'getHomepageTextBlocksEmilieNl' : IDL.Func(
      [],
      [HomepageTextBlocks],
      ['query'],
    ),
  'getIcpAddress' : IDL.Func([], [IDL.Text], ['query']),
  'getIcpEurPrice' : IDL.Func([], [IDL.Float64], []),
  'getIcpEurRate' : IDL.Func([], [IDL.Float64], []),
  'getInflationRatios' : IDL.Func([], [EmojiRatioConfig], ['query']),
  'getInflationStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'lastRunTime' : IDL.Int,
          'automatedCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          'userCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          'launchTime' : IDL.Int,
          'totalEntities' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getInflationSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalAutomated' : IDL.Nat,
          'totalUser' : IDL.Nat,
          'bySection' : IDL.Vec(IDL.Tuple(IDL.Text, EmojiBreakdown)),
        }),
      ],
      ['query'],
    ),
  'getInternationalCustomerCheckoutUrl' : IDL.Func([], [IDL.Text], ['query']),
  'getMaintenanceNoticeEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'getMarktplaatsButtonText' : IDL.Func([], [IDL.Text], ['query']),
  'getMediumUrl' : IDL.Func([], [IDL.Text], ['query']),
  'getMyNewsletterSubscription' : IDL.Func(
      [],
      [IDL.Opt(NewsletterSubscriber)],
      ['query'],
    ),
  'getPayPalButtonText' : IDL.Func([], [IDL.Text], ['query']),
  'getPayPalButtonUrl' : IDL.Func([], [IDL.Text], ['query']),
  'getPaymentCountries' : IDL.Func([], [IDL.Vec(PaymentCountry)], ['query']),
  'getPaymentOptions' : IDL.Func([], [IDL.Vec(PaymentOption)], ['query']),
  'getPaymentOptionsByCountry' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PaymentOption)],
      ['query'],
    ),
  'getPolicyContent' : IDL.Func([PolicyType], [PolicyContent], ['query']),
  'getPopupInstructions' : IDL.Func(
      [],
      [
        IDL.Record({
          'mollieInstruction' : IDL.Text,
          'revolutInstruction' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getProductByKey' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getPromotionalTermsContent' : IDL.Func([], [IDL.Text], ['query']),
  'getPurchaseButtonInstructionalText' : IDL.Func([], [IDL.Text], ['query']),
  'getPurchaseButtonUrl' : IDL.Func([], [IDL.Text], ['query']),
  'getQrCodeImagePath' : IDL.Func([], [IDL.Text], ['query']),
  'getRandomArtProductsLayout' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'x' : IDL.Nat,
          'y' : IDL.Nat,
          'rotation' : IDL.Nat,
          'imageIndex' : IDL.Nat,
        }),
      ],
      [],
    ),
  'getRandomCharacters' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Variant({ 'character' : IDL.Text, 'position' : IDL.Nat }))],
      [],
    ),
  'getRandomEmissionCharacters' : IDL.Func(
      [IDL.Nat, IDL.Variant({ 'left' : IDL.Null, 'right' : IDL.Null })],
      [IDL.Vec(IDL.Text)],
      [],
    ),
  'getRandomGalleryLayout' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'x' : IDL.Nat,
          'y' : IDL.Nat,
          'rotation' : IDL.Nat,
          'imageIndex' : IDL.Nat,
        }),
      ],
      [],
    ),
  'getReflectionBlock' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ReflectionBlock)],
      ['query'],
    ),
  'getReflectionBlocks' : IDL.Func([], [IDL.Vec(ReflectionBlock)], ['query']),
  'getRetailLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getRetailRewards' : IDL.Func([], [IDL.Vec(RewardFull)], ['query']),
  'getReview' : IDL.Func([IDL.Text], [IDL.Opt(Review)], ['query']),
  'getReviewBookTitles' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getReviewEmojiCountsV2' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'like' : IDL.Nat,
          'love' : IDL.Nat,
          'laugh' : IDL.Nat,
          'dislike' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getReviewMilestones' : IDL.Func([], [IDL.Vec(ReviewMilestone)], ['query']),
  'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getReviewsByBookTitle' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'getRevolutPayButtonTextFirstProduct' : IDL.Func([], [IDL.Text], ['query']),
  'getRevolutPayButtonTextSecondProduct' : IDL.Func([], [IDL.Text], ['query']),
  'getRevolutPayButtonUrl' : IDL.Func([], [IDL.Text], ['query']),
  'getRoadmapSectionData' : IDL.Func(
      [],
      [
        IDL.Record({
          'title' : IDL.Text,
          'currentReviews' : IDL.Nat,
          'progressPercentage' : IDL.Nat,
          'description' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getSecondProductPayPalUrl' : IDL.Func([], [IDL.Text], ['query']),
  'getSecondProductPrice' : IDL.Func([], [IDL.Text], ['query']),
  'getSharedPaymentLogos' : IDL.Func(
      [],
      [IDL.Vec(SharedPaymentLogo)],
      ['query'],
    ),
  'getShippingNote' : IDL.Func([], [IDL.Text], ['query']),
  'getSocialLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getSocialRewards' : IDL.Func([], [IDL.Vec(RewardFull)], ['query']),
  'getSpiralFlowerPattern' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text],
      [
        IDL.Record({
          'centerX' : IDL.Nat,
          'centerY' : IDL.Nat,
          'isBlooming' : IDL.Bool,
          'bloomDurationMs' : IDL.Nat,
          'patternId' : IDL.Nat,
          'spiralColor' : IDL.Text,
          'bloomStartTime' : IDL.Int,
        }),
      ],
      [],
    ),
  'getSubmitProofEmail' : IDL.Func([], [IDL.Text], ['query']),
  'getTaxRecords' : IDL.Func([], [IDL.Vec(TaxRecord)], ['query']),
  'getTelegramUrl' : IDL.Func([], [IDL.Text], ['query']),
  'getTiktokUrl' : IDL.Func([], [IDL.Text], ['query']),
  'getUserFavourites' : IDL.Func([], [UserFavourites], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserReviewReactionV2' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getViaMarktplaatsButtonUrl' : IDL.Func([], [IDL.Text], ['query']),
  'getViaVintedButtonUrl' : IDL.Func([], [IDL.Text], ['query']),
  'getVintedButtonText' : IDL.Func([], [IDL.Text], ['query']),
  'getWatermarkedCharacters' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], []),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listDictionaryEntries' : IDL.Func([], [IDL.Vec(DictionaryEntry)], ['query']),
  'listDonations' : IDL.Func([], [IDL.Vec(DonationEntry)], ['query']),
  'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
  'listNewsletterSubscribers' : IDL.Func(
      [],
      [IDL.Vec(NewsletterSubscriber)],
      ['query'],
    ),
  'listShortMessages' : IDL.Func([], [IDL.Vec(ShortMessage)], ['query']),
  'reactToAuthorNote' : IDL.Func(
      [IDL.Text, AuthorNoteReaction],
      [IDL.Variant({ 'ok' : AuthorNote, 'err' : IDL.Text })],
      [],
    ),
  'reactToGame' : IDL.Func([IDL.Text, GameReaction], [IDL.Bool], []),
  'reactToGameAndTrack' : IDL.Func([IDL.Text, GameReaction], [IDL.Bool], []),
  'reactToReflectionBlock' : IDL.Func(
      [IDL.Text, ReflectionBlockReaction],
      [IDL.Variant({ 'ok' : ReflectionBlock, 'err' : IDL.Text })],
      [],
    ),
  'reactToReviewV2' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeAmazonRegionFromBook' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeAnnouncement' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'removeBackgroundMusicTrack' : IDL.Func([IDL.Text], [], []),
  'removeFavourite' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'removeNewsletterSubscriber' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'reorderGalleryCarouselPhotos' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'resetInflationCounts' : IDL.Func([], [], []),
  'saveAmazonRegionForBook' : IDL.Func([IDL.Text, AmazonRegion], [], []),
  'saveAmazonRegionsByBook' : IDL.Func(
      [IDL.Text, IDL.Vec(AmazonRegion)],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveGalleryCarouselPhoto' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setActiveBackgroundMusicTrack' : IDL.Func([IDL.Text], [], []),
  'setAmazonRegions' : IDL.Func([IDL.Vec(AmazonRegion)], [], []),
  'setAnnaAmazonEnabled' : IDL.Func([IDL.Bool], [], []),
  'setAnnaSongAmazonEnabled' : IDL.Func([IDL.Bool], [], []),
  'setAnnouncementRotationInterval' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'setBackgroundMusicEnabled' : IDL.Func([IDL.Bool], [], []),
  'setBackgroundMusicPlaylist' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'setBtcContactEmail' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'setBtcWalletAddress' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'setCryptoSystemEnabled' : IDL.Func([IDL.Bool], [], []),
  'setEmilieAmazonEnabled' : IDL.Func([IDL.Bool], [], []),
  'setEmilieNlAmazonEnabled' : IDL.Func([IDL.Bool], [], []),
  'setEmojiSystemEnabled' : IDL.Func([IDL.Bool], [], []),
  'setEthWalletAddress' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'setIcpWalletAddress' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'setInflationRatios' : IDL.Func([EmojiRatioConfig], [], []),
  'setMaintenanceNoticeEnabled' : IDL.Func([IDL.Bool], [], []),
  'subscribeToNewsletter' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'triggerInflation' : IDL.Func([], [], []),
  'unsubscribeFromNewsletter' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'updateAmazonRegion' : IDL.Func([AmazonRegion], [], []),
  'updateAnnouncement' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'updateArtProduct' : IDL.Func([ArtProduct], [], []),
  'updateAuthorNote' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : AuthorNote, 'err' : IDL.Text })],
      [],
    ),
  'updateBackgroundMusicSettings' : IDL.Func(
      [
        IDL.Record({
          'volume' : IDL.Nat,
          'fadeOutDuration' : IDL.Nat,
          'shouldLoop' : IDL.Bool,
          'fadeInDuration' : IDL.Nat,
        }),
      ],
      [],
      [],
    ),
  'updateBookSale' : IDL.Func([BookSale], [], []),
  'updateBtcExchangeRate' : IDL.Func([IDL.Float64], [], []),
  'updateChallenge' : IDL.Func(
      [
        IDL.Text,
        ChallengeCategory,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Variant({ 'ok' : ExperienceChallenge, 'err' : IDL.Text })],
      [],
    ),
  'updateCopyrightSettings' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateCurrentReviewNumber' : IDL.Func([IDL.Nat], [], []),
  'updateDictionaryEntry' : IDL.Func([DictionaryEntry], [], []),
  'updateDonation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'updateExperienceHubTexts' : IDL.Func([ExperienceHubTexts], [], []),
  'updateFooterSettings' : IDL.Func([FooterSettings], [], []),
  'updateGame' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Vec(IDL.Text)),
      ],
      [IDL.Bool],
      [],
    ),
  'updateHomepageTextBlocks' : IDL.Func(
      [
        IDL.Record({
          'block1' : TextBlock,
          'block2' : TextBlock,
          'block3' : TextBlock,
        }),
      ],
      [],
      [],
    ),
  'updateHomepageTextBlocksAnnaEn' : IDL.Func([HomepageTextBlocks], [], []),
  'updateHomepageTextBlocksAnnaNl' : IDL.Func([HomepageTextBlocks], [], []),
  'updateHomepageTextBlocksEmilieEn' : IDL.Func([HomepageTextBlocks], [], []),
  'updateHomepageTextBlocksEmilieNl' : IDL.Func([HomepageTextBlocks], [], []),
  'updatePaymentCountry' : IDL.Func([PaymentCountry], [IDL.Bool], []),
  'updatePaymentOption' : IDL.Func([PaymentOption], [IDL.Bool], []),
  'updatePolicyContent' : IDL.Func([PolicyType, IDL.Text], [], []),
  'updateProductByKey' : IDL.Func([IDL.Text, Product], [IDL.Bool], []),
  'updatePromotionalTermsContent' : IDL.Func([IDL.Text], [], []),
  'updateReflectionBlock' : IDL.Func([ReflectionBlock], [], []),
  'updateRetailLeaderboardEntry' : IDL.Func([LeaderboardEntry], [], []),
  'updateReview' : IDL.Func([Review], [], []),
  'updateReviewMilestone' : IDL.Func([ReviewMilestone], [], []),
  'updateReward' : IDL.Func([RewardInput], [], []),
  'updateSharedPaymentLogo' : IDL.Func([SharedPaymentLogo], [IDL.Bool], []),
  'updateShortMessage' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : ShortMessage, 'err' : IDL.Text })],
      [],
    ),
  'updateSocialLeaderboardEntry' : IDL.Func([LeaderboardEntry], [], []),
  'updateSubmitProofEmail' : IDL.Func([IDL.Text], [], []),
  'updateTaxRecord' : IDL.Func([TaxRecord], [], []),
  'uploadBackgroundMusicTrack' : IDL.Func([BackgroundMusicTrack], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AmazonRegion = IDL.Record({
    'id' : IDL.Text,
    'country' : IDL.Text,
    'domain' : IDL.Text,
    'kindleLink' : IDL.Text,
    'currencySymbol' : IDL.Text,
    'paperbackButtonText' : IDL.Text,
    'hardcoverButtonText' : IDL.Text,
    'kindleButtonColor' : IDL.Text,
    'paperbackPrice' : IDL.Text,
    'enabled' : IDL.Bool,
    'hardcoverButtonColor' : IDL.Text,
    'hardcoverLink' : IDL.Text,
    'kindleButtonText' : IDL.Text,
    'kindleFontColor' : IDL.Text,
    'paperbackLink' : IDL.Text,
    'showKindleUnlimited' : IDL.Bool,
    'hardcoverPrice' : IDL.Text,
    'paperbackFontColor' : IDL.Text,
    'paperbackButtonColor' : IDL.Text,
    'hardcoverFontColor' : IDL.Text,
    'kindlePrice' : IDL.Text,
  });
  const ArtProduct = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'imagePath' : IDL.Opt(IDL.Text),
    'purchaseLink' : IDL.Text,
  });
  const AuthorNote = IDL.Record({
    'id' : IDL.Text,
    'poemSubtitle' : IDL.Text,
    'noteText' : IDL.Text,
    'poemTitle' : IDL.Text,
    'reactions' : IDL.Record({
      'like' : IDL.Nat,
      'love' : IDL.Nat,
      'laugh' : IDL.Nat,
      'dislike' : IDL.Nat,
    }),
  });
  const BookSale = IDL.Record({
    'customerName' : IDL.Opt(IDL.Text),
    'salesAmount' : IDL.Nat,
    'bookNumber' : IDL.Nat,
  });
  const ChallengeCategory = IDL.Variant({
    'retail' : IDL.Null,
    'social' : IDL.Null,
  });
  const ExperienceChallenge = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'specialReward' : IDL.Opt(IDL.Text),
    'rewardPoints' : IDL.Nat,
    'description' : IDL.Text,
    'category' : ChallengeCategory,
  });
  const DictionaryEntry = IDL.Record({
    'meaning' : IDL.Text,
    'word' : IDL.Text,
    'etymology' : IDL.Text,
    'examples' : IDL.Text,
  });
  const PaymentCountry = IDL.Record({
    'id' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'continent' : IDL.Text,
    'enabled' : IDL.Bool,
  });
  const PaymentOption = IDL.Record({
    'id' : IDL.Text,
    'methodName' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'link' : IDL.Text,
    'logoStorageKey' : IDL.Text,
    'countryId' : IDL.Text,
    'enabled' : IDL.Bool,
    'logoUrl' : IDL.Text,
    'shippingEuro' : IDL.Text,
    'buttonColor' : IDL.Text,
    'priceEuro' : IDL.Text,
    'fontColor' : IDL.Text,
    'buzzingEnabled' : IDL.Bool,
  });
  const ReflectionBlock = IDL.Record({
    'id' : IDL.Text,
    'poemTitle' : IDL.Text,
    'reactions' : IDL.Opt(
      IDL.Record({
        'like' : IDL.Nat,
        'love' : IDL.Nat,
        'laugh' : IDL.Nat,
        'dislike' : IDL.Nat,
      })
    ),
    'reflectionChallenges' : IDL.Vec(IDL.Text),
  });
  const LeaderboardEntry = IDL.Record({
    'id' : IDL.Text,
    'photoPath' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'score' : IDL.Nat,
  });
  const Review = IDL.Record({
    'id' : IDL.Text,
    'bookTitle' : IDL.Text,
    'photoPath' : IDL.Opt(IDL.Text),
    'starRating' : IDL.Opt(IDL.Nat),
    'pageNumbers' : IDL.Text,
    'fullText' : IDL.Text,
    'reviewerName' : IDL.Text,
    'snippet' : IDL.Text,
    'sourceLink' : IDL.Opt(IDL.Text),
    'poemSubTitle' : IDL.Text,
    'poemTitle' : IDL.Text,
    'companyBlogSite' : IDL.Opt(IDL.Text),
    'videoUrl' : IDL.Opt(IDL.Text),
    'reactions' : IDL.Opt(
      IDL.Record({
        'like' : IDL.Nat,
        'love' : IDL.Nat,
        'laugh' : IDL.Nat,
        'dislike' : IDL.Nat,
      })
    ),
  });
  const ReviewMilestone = IDL.Record({
    'prizeImagePath' : IDL.Opt(IDL.Text),
    'milestone' : IDL.Nat,
  });
  const RewardInput = IDL.Record({
    'id' : IDL.Text,
    'photoPath' : IDL.Opt(IDL.Text),
    'pageType' : IDL.Variant({ 'retail' : IDL.Null, 'social' : IDL.Null }),
    'description' : IDL.Text,
    'availableCount' : IDL.Opt(IDL.Nat),
    'rewardType' : IDL.Variant({
      'referral' : IDL.Null,
      'other' : IDL.Null,
      'points' : IDL.Null,
    }),
    'claimEmail' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
  });
  const SharedPaymentLogo = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'logoStorageKey' : IDL.Text,
    'logoUrl' : IDL.Text,
  });
  const ShortMessage = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
  });
  const Quarter = IDL.Variant({
    'q1' : IDL.Null,
    'q2' : IDL.Null,
    'q3' : IDL.Null,
    'q4' : IDL.Null,
  });
  const TaxRecord = IDL.Record({
    'salesAmount' : IDL.Nat,
    'quarter' : Quarter,
    'year' : IDL.Nat,
    'taxAmount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const FileReference = IDL.Record({ 'hash' : IDL.Text, 'path' : IDL.Text });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'message' : IDL.Text,
  });
  const BackgroundMusicTrack = IDL.Record({
    'title' : IDL.Text,
    'path' : IDL.Text,
    'uploadTimestamp' : IDL.Int,
    'isActive' : IDL.Bool,
    'artist' : IDL.Text,
  });
  const BackgroundMusicState = IDL.Record({
    'musicEnabled' : IDL.Bool,
    'tracks' : IDL.Vec(BackgroundMusicTrack),
    'playlist' : IDL.Vec(IDL.Text),
    'currentPlaylistIndex' : IDL.Nat,
    'activeTrack' : IDL.Opt(IDL.Text),
    'settings' : IDL.Record({
      'volume' : IDL.Nat,
      'fadeOutDuration' : IDL.Nat,
      'shouldLoop' : IDL.Bool,
      'fadeInDuration' : IDL.Nat,
    }),
  });
  const BolBanner = IDL.Record({ 'imagePath' : IDL.Text, 'link' : IDL.Text });
  const GameReaction = IDL.Variant({
    'like' : IDL.Null,
    'love' : IDL.Null,
    'laugh' : IDL.Null,
    'dislike' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'favouriteReflections' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'favouriteVocabulary' : IDL.Vec(IDL.Text),
    'favouriteShortMessages' : IDL.Vec(IDL.Text),
    'favouriteGames' : IDL.Vec(IDL.Text),
    'favouriteAuthorNotes' : IDL.Vec(IDL.Text),
  });
  const ExperienceHubTexts = IDL.Record({
    'mainSubtitle' : IDL.Text,
    'socialPageSubtitle' : IDL.Text,
    'retailCardDescription' : IDL.Text,
    'gamesPageSubtitle' : IDL.Text,
    'retailPageSubtitle' : IDL.Text,
    'socialCardDescription' : IDL.Text,
    'gamesCardDescription' : IDL.Text,
  });
  const FooterSettings = IDL.Record({
    'businessKvk' : IDL.Text,
    'businessIban' : IDL.Text,
    'businessName' : IDL.Text,
    'businessEmail' : IDL.Text,
    'businessAddress' : IDL.Text,
    'footerCaption' : IDL.Text,
    'businessPhone' : IDL.Text,
    'businessTaxId' : IDL.Text,
  });
  const GalleryCarouselPhoto = IDL.Record({
    'id' : IDL.Text,
    'linkUrl' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'path' : IDL.Text,
    'side' : IDL.Text,
  });
  const GameComment = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'authorName' : IDL.Text,
    'gameId' : IDL.Text,
    'commentText' : IDL.Text,
    'authorPrincipal' : IDL.Text,
  });
  const GameReactionCounts = IDL.Record({
    'like' : IDL.Nat,
    'love' : IDL.Nat,
    'laugh' : IDL.Nat,
    'dislike' : IDL.Nat,
  });
  const Game = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'playerCount' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'gameType' : IDL.Text,
    'materialsRequired' : IDL.Text,
    'rules' : IDL.Vec(IDL.Text),
  });
  const TextBlock = IDL.Record({ 'title' : IDL.Text, 'content' : IDL.Text });
  const HomepageTextBlocks = IDL.Record({
    'block1' : TextBlock,
    'block2' : TextBlock,
    'block3' : TextBlock,
  });
  const EmojiRatioConfig = IDL.Record({
    'loveMax' : IDL.Nat,
    'loveMin' : IDL.Nat,
    'laughMax' : IDL.Nat,
    'laughMin' : IDL.Nat,
    'likeMax' : IDL.Nat,
    'likeMin' : IDL.Nat,
    'dislikeMax' : IDL.Nat,
    'dislikeMin' : IDL.Nat,
  });
  const EmojiBreakdown = IDL.Record({
    'userLike' : IDL.Nat,
    'userLove' : IDL.Nat,
    'userLaugh' : IDL.Nat,
    'autoLike' : IDL.Nat,
    'autoLove' : IDL.Nat,
    'autoLaugh' : IDL.Nat,
    'userDislike' : IDL.Nat,
    'autoDislike' : IDL.Nat,
  });
  const NewsletterSubscriber = IDL.Record({
    'subscribedAt' : IDL.Int,
    'email' : IDL.Text,
    'principalId' : IDL.Text,
  });
  const PolicyType = IDL.Variant({
    'refundAndReturn' : IDL.Null,
    'privacyPolicy' : IDL.Null,
    'shippingAndDelivery' : IDL.Null,
    'termsAndConditions' : IDL.Null,
    'disclaimerLiability' : IDL.Null,
    'cookiePolicy' : IDL.Null,
    'intellectualProperty' : IDL.Null,
    'promotionalTerms' : IDL.Null,
  });
  const PolicyContent = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'policyType' : PolicyType,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'hasCustomImage' : IDL.Bool,
    'description' : IDL.Text,
    'editionType' : IDL.Text,
    'price' : IDL.Nat,
    'frontCoverImagePath' : IDL.Opt(IDL.Text),
    'images' : IDL.Vec(IDL.Text),
  });
  const RewardFull = IDL.Record({
    'id' : IDL.Text,
    'photoPath' : IDL.Opt(IDL.Text),
    'pageType' : IDL.Variant({ 'retail' : IDL.Null, 'social' : IDL.Null }),
    'description' : IDL.Text,
    'availableCount' : IDL.Opt(IDL.Nat),
    'rewardType' : IDL.Variant({
      'referral' : IDL.Null,
      'other' : IDL.Null,
      'points' : IDL.Null,
    }),
    'claimEmail' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
  });
  const UserFavourites = IDL.Record({
    'shortMessages' : IDL.Vec(IDL.Text),
    'authorNotes' : IDL.Vec(IDL.Text),
    'reflections' : IDL.Vec(IDL.Text),
    'games' : IDL.Vec(IDL.Text),
    'vocabulary' : IDL.Vec(IDL.Text),
  });
  const DonationEntry = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'column' : IDL.Nat,
    'position' : IDL.Nat,
  });
  const AuthorNoteReaction = IDL.Variant({
    'like' : IDL.Null,
    'love' : IDL.Null,
    'laugh' : IDL.Null,
    'dislike' : IDL.Null,
  });
  const ReflectionBlockReaction = IDL.Variant({
    'like' : IDL.Null,
    'love' : IDL.Null,
    'laugh' : IDL.Null,
    'dislike' : IDL.Null,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addAmazonRegion' : IDL.Func([AmazonRegion], [], []),
    'addAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'addArtProduct' : IDL.Func([ArtProduct], [], []),
    'addAuthorNote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : AuthorNote, 'err' : IDL.Text })],
        [],
      ),
    'addBookSale' : IDL.Func([BookSale], [], []),
    'addChallenge' : IDL.Func(
        [ChallengeCategory, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : ExperienceChallenge, 'err' : IDL.Text })],
        [],
      ),
    'addDictionaryEntry' : IDL.Func([DictionaryEntry], [], []),
    'addDonation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'addFavourite' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'addGame' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [IDL.Text],
        [],
      ),
    'addGameComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'addPaymentCountry' : IDL.Func([PaymentCountry], [IDL.Bool], []),
    'addPaymentOption' : IDL.Func([PaymentOption], [IDL.Bool], []),
    'addReflectionBlock' : IDL.Func([ReflectionBlock], [], []),
    'addRetailLeaderboardEntry' : IDL.Func([LeaderboardEntry], [], []),
    'addReview' : IDL.Func([Review], [], []),
    'addReviewMilestone' : IDL.Func([ReviewMilestone], [], []),
    'addReward' : IDL.Func([RewardInput], [], []),
    'addSharedPaymentLogo' : IDL.Func([SharedPaymentLogo], [IDL.Bool], []),
    'addShortMessage' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : ShortMessage, 'err' : IDL.Text })],
        [],
      ),
    'addSocialLeaderboardEntry' : IDL.Func([LeaderboardEntry], [], []),
    'addTaxRecord' : IDL.Func([TaxRecord], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateTax' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'createEmissionEffectAnimation' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Record({ 'animationId' : IDL.Nat })],
        [],
      ),
    'deactivateBackgroundMusicTrack' : IDL.Func([IDL.Text], [], []),
    'deleteAmazonRegion' : IDL.Func([IDL.Text], [], []),
    'deleteArtProduct' : IDL.Func([IDL.Text], [], []),
    'deleteAuthorNote' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteBookSale' : IDL.Func([IDL.Nat], [], []),
    'deleteChallenge' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteDictionaryEntry' : IDL.Func([IDL.Text], [], []),
    'deleteDonation' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteGalleryCarouselPhoto' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteGame' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteGameComment' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deletePaymentCountry' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deletePaymentOption' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteReflectionBlock' : IDL.Func([IDL.Text], [], []),
    'deleteRetailLeaderboardEntry' : IDL.Func([IDL.Text], [], []),
    'deleteReview' : IDL.Func([IDL.Text], [], []),
    'deleteReviewMilestone' : IDL.Func([IDL.Nat], [], []),
    'deleteReward' : IDL.Func([IDL.Text], [], []),
    'deleteSharedPaymentLogo' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteShortMessage' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteSocialLeaderboardEntry' : IDL.Func([IDL.Text], [], []),
    'deleteTaxRecord' : IDL.Func([IDL.Nat, Quarter], [], []),
    'distributeEmojiManually' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'dropFileReference' : IDL.Func([IDL.Text], [], []),
    'ensureBitcoinForAllCountries' : IDL.Func([], [], []),
    'ensureCreditcardForAllCountries' : IDL.Func([], [], []),
    'ensureEthereumForAllCountries' : IDL.Func([], [], []),
    'ensureIcpForAllCountries' : IDL.Func([], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getActiveBackgroundMusicTrack' : IDL.Func(
        [],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getAllFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
    'getAmazonRegion' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AmazonRegion)],
        ['query'],
      ),
    'getAmazonRegionForBook' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(AmazonRegion)],
        ['query'],
      ),
    'getAmazonRegions' : IDL.Func([], [IDL.Vec(AmazonRegion)], ['query']),
    'getAmazonRegionsByBook' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AmazonRegion)],
        ['query'],
      ),
    'getAnnaAmazonEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'getAnnaSongAmazonEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'getAnnouncementRotationInterval' : IDL.Func([], [IDL.Nat], ['query']),
    'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getApproximateBtcAmount' : IDL.Func(
        [IDL.Float64],
        [IDL.Float64],
        ['query'],
      ),
    'getArtProduct' : IDL.Func([IDL.Text], [IDL.Opt(ArtProduct)], ['query']),
    'getArtProducts' : IDL.Func([], [IDL.Vec(ArtProduct)], ['query']),
    'getArtProductsSectionData' : IDL.Func(
        [],
        [IDL.Record({ 'description' : IDL.Text })],
        ['query'],
      ),
    'getAuthorNotes' : IDL.Func([], [IDL.Vec(AuthorNote)], ['query']),
    'getBackgroundMusic' : IDL.Func([], [BackgroundMusicState], ['query']),
    'getBackgroundMusicEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'getBackgroundMusicSettings' : IDL.Func(
        [],
        [
          IDL.Record({
            'volume' : IDL.Nat,
            'fadeOutDuration' : IDL.Nat,
            'shouldLoop' : IDL.Bool,
            'fadeInDuration' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getBackgroundMusicTracks' : IDL.Func(
        [],
        [IDL.Vec(BackgroundMusicTrack)],
        ['query'],
      ),
    'getBitcoinInstructionText' : IDL.Func([], [IDL.Text], ['query']),
    'getBitcoinPaymentAmount' : IDL.Func(
        [],
        [IDL.Record({ 'currency' : IDL.Text, 'amount' : IDL.Text })],
        ['query'],
      ),
    'getBitcoinPaymentConfig' : IDL.Func(
        [],
        [IDL.Record({ 'walletAddress' : IDL.Text, 'contactEmail' : IDL.Text })],
        ['query'],
      ),
    'getBitcoinPaymentDetails' : IDL.Func(
        [],
        [
          IDL.Record({
            'qrCodeImagePath' : IDL.Text,
            'btcEurAmount' : IDL.Text,
            'btcAddress' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getBitcoinPaymentModalState' : IDL.Func(
        [],
        [IDL.Record({ 'isOpen' : IDL.Bool, 'lastUpdateTimestamp' : IDL.Int })],
        ['query'],
      ),
    'getBolBanner' : IDL.Func([], [BolBanner], ['query']),
    'getBoldedDeliveryInfoText' : IDL.Func([], [IDL.Text], ['query']),
    'getBookSales' : IDL.Func([], [IDL.Vec(BookSale)], ['query']),
    'getBtcAddress' : IDL.Func([], [IDL.Text], ['query']),
    'getBtcEurPrice' : IDL.Func([], [IDL.Float64], []),
    'getBtcEurRate' : IDL.Func([], [IDL.Float64], []),
    'getBtcExchangeRate' : IDL.Func([], [IDL.Opt(IDL.Float64)], ['query']),
    'getBtcOrangeColor' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerGameReaction' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GameReaction)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChallenges' : IDL.Func([], [IDL.Vec(ExperienceChallenge)], ['query']),
    'getChallengesByCategory' : IDL.Func(
        [ChallengeCategory],
        [IDL.Vec(ExperienceChallenge)],
        ['query'],
      ),
    'getCopyrightSettings' : IDL.Func(
        [],
        [
          IDL.Record({
            'copyrightStartYear' : IDL.Nat,
            'copyrightLine' : IDL.Text,
            'copyrightYearColor' : IDL.Text,
            'copyrightLegalText' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getCryptoRates' : IDL.Func(
        [],
        [
          IDL.Record({
            'btc' : IDL.Float64,
            'eth' : IDL.Float64,
            'icp' : IDL.Float64,
          }),
        ],
        [],
      ),
    'getCryptoSystemEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'getCurrentReviewNumber' : IDL.Func([], [IDL.Nat], ['query']),
    'getDefaultArtProducts' : IDL.Func([], [IDL.Vec(ArtProduct)], ['query']),
    'getDefaultImageStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'qrCodePath' : IDL.Text,
            'bolBannerPath' : IDL.Text,
            'bolBannerRegistered' : IDL.Bool,
            'qrCodeRegistered' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getDefaultReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getDictionaryEntry' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DictionaryEntry)],
        ['query'],
      ),
    'getDisclaimerText' : IDL.Func([], [IDL.Text], ['query']),
    'getDiscordUrl' : IDL.Func([], [IDL.Text], ['query']),
    'getDistributionPreview' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getEmilieAmazonEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'getEmilieNlAmazonEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'getEmojiSystemEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'getEthAddress' : IDL.Func([], [IDL.Text], ['query']),
    'getEthEurPrice' : IDL.Func([], [IDL.Float64], []),
    'getEthEurRate' : IDL.Func([], [IDL.Float64], []),
    'getExperienceHubTexts' : IDL.Func([], [ExperienceHubTexts], ['query']),
    'getFeaturedProductButtonTexts' : IDL.Func(
        [],
        [
          IDL.Record({
            'secondProductButtonText' : IDL.Text,
            'firstProductButtonText' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getFileReference' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(FileReference)],
        ['query'],
      ),
    'getFirstProductPrice' : IDL.Func([], [IDL.Text], ['query']),
    'getFooterCopyright' : IDL.Func([], [IDL.Text], ['query']),
    'getFooterSettings' : IDL.Func([], [FooterSettings], ['query']),
    'getGalleryCarouselPhotos' : IDL.Func(
        [],
        [IDL.Vec(GalleryCarouselPhoto)],
        ['query'],
      ),
    'getGameComments' : IDL.Func([IDL.Text], [IDL.Vec(GameComment)], ['query']),
    'getGameReactionCounts' : IDL.Func(
        [IDL.Text],
        [GameReactionCounts],
        ['query'],
      ),
    'getGameReactionCountsInflated' : IDL.Func(
        [IDL.Text],
        [GameReactionCounts],
        ['query'],
      ),
    'getGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'getHomepageTextBlocks' : IDL.Func(
        [],
        [
          IDL.Record({
            'block1' : TextBlock,
            'block2' : TextBlock,
            'block3' : TextBlock,
          }),
        ],
        ['query'],
      ),
    'getHomepageTextBlocksAnnaEn' : IDL.Func(
        [],
        [HomepageTextBlocks],
        ['query'],
      ),
    'getHomepageTextBlocksAnnaNl' : IDL.Func(
        [],
        [HomepageTextBlocks],
        ['query'],
      ),
    'getHomepageTextBlocksEmilieEn' : IDL.Func(
        [],
        [HomepageTextBlocks],
        ['query'],
      ),
    'getHomepageTextBlocksEmilieNl' : IDL.Func(
        [],
        [HomepageTextBlocks],
        ['query'],
      ),
    'getIcpAddress' : IDL.Func([], [IDL.Text], ['query']),
    'getIcpEurPrice' : IDL.Func([], [IDL.Float64], []),
    'getIcpEurRate' : IDL.Func([], [IDL.Float64], []),
    'getInflationRatios' : IDL.Func([], [EmojiRatioConfig], ['query']),
    'getInflationStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'lastRunTime' : IDL.Int,
            'automatedCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
            'userCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
            'launchTime' : IDL.Int,
            'totalEntities' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getInflationSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalAutomated' : IDL.Nat,
            'totalUser' : IDL.Nat,
            'bySection' : IDL.Vec(IDL.Tuple(IDL.Text, EmojiBreakdown)),
          }),
        ],
        ['query'],
      ),
    'getInternationalCustomerCheckoutUrl' : IDL.Func([], [IDL.Text], ['query']),
    'getMaintenanceNoticeEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'getMarktplaatsButtonText' : IDL.Func([], [IDL.Text], ['query']),
    'getMediumUrl' : IDL.Func([], [IDL.Text], ['query']),
    'getMyNewsletterSubscription' : IDL.Func(
        [],
        [IDL.Opt(NewsletterSubscriber)],
        ['query'],
      ),
    'getPayPalButtonText' : IDL.Func([], [IDL.Text], ['query']),
    'getPayPalButtonUrl' : IDL.Func([], [IDL.Text], ['query']),
    'getPaymentCountries' : IDL.Func([], [IDL.Vec(PaymentCountry)], ['query']),
    'getPaymentOptions' : IDL.Func([], [IDL.Vec(PaymentOption)], ['query']),
    'getPaymentOptionsByCountry' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PaymentOption)],
        ['query'],
      ),
    'getPolicyContent' : IDL.Func([PolicyType], [PolicyContent], ['query']),
    'getPopupInstructions' : IDL.Func(
        [],
        [
          IDL.Record({
            'mollieInstruction' : IDL.Text,
            'revolutInstruction' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getProductByKey' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getPromotionalTermsContent' : IDL.Func([], [IDL.Text], ['query']),
    'getPurchaseButtonInstructionalText' : IDL.Func([], [IDL.Text], ['query']),
    'getPurchaseButtonUrl' : IDL.Func([], [IDL.Text], ['query']),
    'getQrCodeImagePath' : IDL.Func([], [IDL.Text], ['query']),
    'getRandomArtProductsLayout' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'x' : IDL.Nat,
            'y' : IDL.Nat,
            'rotation' : IDL.Nat,
            'imageIndex' : IDL.Nat,
          }),
        ],
        [],
      ),
    'getRandomCharacters' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Vec(
            IDL.Variant({ 'character' : IDL.Text, 'position' : IDL.Nat })
          ),
        ],
        [],
      ),
    'getRandomEmissionCharacters' : IDL.Func(
        [IDL.Nat, IDL.Variant({ 'left' : IDL.Null, 'right' : IDL.Null })],
        [IDL.Vec(IDL.Text)],
        [],
      ),
    'getRandomGalleryLayout' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'x' : IDL.Nat,
            'y' : IDL.Nat,
            'rotation' : IDL.Nat,
            'imageIndex' : IDL.Nat,
          }),
        ],
        [],
      ),
    'getReflectionBlock' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ReflectionBlock)],
        ['query'],
      ),
    'getReflectionBlocks' : IDL.Func([], [IDL.Vec(ReflectionBlock)], ['query']),
    'getRetailLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getRetailRewards' : IDL.Func([], [IDL.Vec(RewardFull)], ['query']),
    'getReview' : IDL.Func([IDL.Text], [IDL.Opt(Review)], ['query']),
    'getReviewBookTitles' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getReviewEmojiCountsV2' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'like' : IDL.Nat,
            'love' : IDL.Nat,
            'laugh' : IDL.Nat,
            'dislike' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getReviewMilestones' : IDL.Func([], [IDL.Vec(ReviewMilestone)], ['query']),
    'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getReviewsByBookTitle' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'getRevolutPayButtonTextFirstProduct' : IDL.Func([], [IDL.Text], ['query']),
    'getRevolutPayButtonTextSecondProduct' : IDL.Func(
        [],
        [IDL.Text],
        ['query'],
      ),
    'getRevolutPayButtonUrl' : IDL.Func([], [IDL.Text], ['query']),
    'getRoadmapSectionData' : IDL.Func(
        [],
        [
          IDL.Record({
            'title' : IDL.Text,
            'currentReviews' : IDL.Nat,
            'progressPercentage' : IDL.Nat,
            'description' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getSecondProductPayPalUrl' : IDL.Func([], [IDL.Text], ['query']),
    'getSecondProductPrice' : IDL.Func([], [IDL.Text], ['query']),
    'getSharedPaymentLogos' : IDL.Func(
        [],
        [IDL.Vec(SharedPaymentLogo)],
        ['query'],
      ),
    'getShippingNote' : IDL.Func([], [IDL.Text], ['query']),
    'getSocialLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getSocialRewards' : IDL.Func([], [IDL.Vec(RewardFull)], ['query']),
    'getSpiralFlowerPattern' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text],
        [
          IDL.Record({
            'centerX' : IDL.Nat,
            'centerY' : IDL.Nat,
            'isBlooming' : IDL.Bool,
            'bloomDurationMs' : IDL.Nat,
            'patternId' : IDL.Nat,
            'spiralColor' : IDL.Text,
            'bloomStartTime' : IDL.Int,
          }),
        ],
        [],
      ),
    'getSubmitProofEmail' : IDL.Func([], [IDL.Text], ['query']),
    'getTaxRecords' : IDL.Func([], [IDL.Vec(TaxRecord)], ['query']),
    'getTelegramUrl' : IDL.Func([], [IDL.Text], ['query']),
    'getTiktokUrl' : IDL.Func([], [IDL.Text], ['query']),
    'getUserFavourites' : IDL.Func([], [UserFavourites], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserReviewReactionV2' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getViaMarktplaatsButtonUrl' : IDL.Func([], [IDL.Text], ['query']),
    'getViaVintedButtonUrl' : IDL.Func([], [IDL.Text], ['query']),
    'getVintedButtonText' : IDL.Func([], [IDL.Text], ['query']),
    'getWatermarkedCharacters' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], []),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listDictionaryEntries' : IDL.Func(
        [],
        [IDL.Vec(DictionaryEntry)],
        ['query'],
      ),
    'listDonations' : IDL.Func([], [IDL.Vec(DonationEntry)], ['query']),
    'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
    'listNewsletterSubscribers' : IDL.Func(
        [],
        [IDL.Vec(NewsletterSubscriber)],
        ['query'],
      ),
    'listShortMessages' : IDL.Func([], [IDL.Vec(ShortMessage)], ['query']),
    'reactToAuthorNote' : IDL.Func(
        [IDL.Text, AuthorNoteReaction],
        [IDL.Variant({ 'ok' : AuthorNote, 'err' : IDL.Text })],
        [],
      ),
    'reactToGame' : IDL.Func([IDL.Text, GameReaction], [IDL.Bool], []),
    'reactToGameAndTrack' : IDL.Func([IDL.Text, GameReaction], [IDL.Bool], []),
    'reactToReflectionBlock' : IDL.Func(
        [IDL.Text, ReflectionBlockReaction],
        [IDL.Variant({ 'ok' : ReflectionBlock, 'err' : IDL.Text })],
        [],
      ),
    'reactToReviewV2' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeAmazonRegionFromBook' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeAnnouncement' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'removeBackgroundMusicTrack' : IDL.Func([IDL.Text], [], []),
    'removeFavourite' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'removeNewsletterSubscriber' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'reorderGalleryCarouselPhotos' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'resetInflationCounts' : IDL.Func([], [], []),
    'saveAmazonRegionForBook' : IDL.Func([IDL.Text, AmazonRegion], [], []),
    'saveAmazonRegionsByBook' : IDL.Func(
        [IDL.Text, IDL.Vec(AmazonRegion)],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveGalleryCarouselPhoto' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setActiveBackgroundMusicTrack' : IDL.Func([IDL.Text], [], []),
    'setAmazonRegions' : IDL.Func([IDL.Vec(AmazonRegion)], [], []),
    'setAnnaAmazonEnabled' : IDL.Func([IDL.Bool], [], []),
    'setAnnaSongAmazonEnabled' : IDL.Func([IDL.Bool], [], []),
    'setAnnouncementRotationInterval' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'setBackgroundMusicEnabled' : IDL.Func([IDL.Bool], [], []),
    'setBackgroundMusicPlaylist' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'setBtcContactEmail' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'setBtcWalletAddress' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'setCryptoSystemEnabled' : IDL.Func([IDL.Bool], [], []),
    'setEmilieAmazonEnabled' : IDL.Func([IDL.Bool], [], []),
    'setEmilieNlAmazonEnabled' : IDL.Func([IDL.Bool], [], []),
    'setEmojiSystemEnabled' : IDL.Func([IDL.Bool], [], []),
    'setEthWalletAddress' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'setIcpWalletAddress' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'setInflationRatios' : IDL.Func([EmojiRatioConfig], [], []),
    'setMaintenanceNoticeEnabled' : IDL.Func([IDL.Bool], [], []),
    'subscribeToNewsletter' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'triggerInflation' : IDL.Func([], [], []),
    'unsubscribeFromNewsletter' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'updateAmazonRegion' : IDL.Func([AmazonRegion], [], []),
    'updateAnnouncement' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'updateArtProduct' : IDL.Func([ArtProduct], [], []),
    'updateAuthorNote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : AuthorNote, 'err' : IDL.Text })],
        [],
      ),
    'updateBackgroundMusicSettings' : IDL.Func(
        [
          IDL.Record({
            'volume' : IDL.Nat,
            'fadeOutDuration' : IDL.Nat,
            'shouldLoop' : IDL.Bool,
            'fadeInDuration' : IDL.Nat,
          }),
        ],
        [],
        [],
      ),
    'updateBookSale' : IDL.Func([BookSale], [], []),
    'updateBtcExchangeRate' : IDL.Func([IDL.Float64], [], []),
    'updateChallenge' : IDL.Func(
        [
          IDL.Text,
          ChallengeCategory,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : ExperienceChallenge, 'err' : IDL.Text })],
        [],
      ),
    'updateCopyrightSettings' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateCurrentReviewNumber' : IDL.Func([IDL.Nat], [], []),
    'updateDictionaryEntry' : IDL.Func([DictionaryEntry], [], []),
    'updateDonation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'updateExperienceHubTexts' : IDL.Func([ExperienceHubTexts], [], []),
    'updateFooterSettings' : IDL.Func([FooterSettings], [], []),
    'updateGame' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Vec(IDL.Text)),
        ],
        [IDL.Bool],
        [],
      ),
    'updateHomepageTextBlocks' : IDL.Func(
        [
          IDL.Record({
            'block1' : TextBlock,
            'block2' : TextBlock,
            'block3' : TextBlock,
          }),
        ],
        [],
        [],
      ),
    'updateHomepageTextBlocksAnnaEn' : IDL.Func([HomepageTextBlocks], [], []),
    'updateHomepageTextBlocksAnnaNl' : IDL.Func([HomepageTextBlocks], [], []),
    'updateHomepageTextBlocksEmilieEn' : IDL.Func([HomepageTextBlocks], [], []),
    'updateHomepageTextBlocksEmilieNl' : IDL.Func([HomepageTextBlocks], [], []),
    'updatePaymentCountry' : IDL.Func([PaymentCountry], [IDL.Bool], []),
    'updatePaymentOption' : IDL.Func([PaymentOption], [IDL.Bool], []),
    'updatePolicyContent' : IDL.Func([PolicyType, IDL.Text], [], []),
    'updateProductByKey' : IDL.Func([IDL.Text, Product], [IDL.Bool], []),
    'updatePromotionalTermsContent' : IDL.Func([IDL.Text], [], []),
    'updateReflectionBlock' : IDL.Func([ReflectionBlock], [], []),
    'updateRetailLeaderboardEntry' : IDL.Func([LeaderboardEntry], [], []),
    'updateReview' : IDL.Func([Review], [], []),
    'updateReviewMilestone' : IDL.Func([ReviewMilestone], [], []),
    'updateReward' : IDL.Func([RewardInput], [], []),
    'updateSharedPaymentLogo' : IDL.Func([SharedPaymentLogo], [IDL.Bool], []),
    'updateShortMessage' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : ShortMessage, 'err' : IDL.Text })],
        [],
      ),
    'updateSocialLeaderboardEntry' : IDL.Func([LeaderboardEntry], [], []),
    'updateSubmitProofEmail' : IDL.Func([IDL.Text], [], []),
    'updateTaxRecord' : IDL.Func([TaxRecord], [], []),
    'uploadBackgroundMusicTrack' : IDL.Func([BackgroundMusicTrack], [], []),
  });
};

export const init = ({ IDL }) => { return []; };